-- MySQL Script generated by MySQL Workbench
-- Wed Oct 20 17:15:08 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema CarClub
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CarClub
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CarClub` ;
USE `CarClub` ;

-- -----------------------------------------------------
-- Table `CarClub`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarClub`.`User` (
  `Id` BIGINT NOT NULL,
  `Key` VARCHAR(64) NOT NULL,
  `Email` VARCHAR(128) CHARACTER SET 'utf8mb4' NOT NULL,
  `Password` VARCHAR(128) CHARACTER SET 'utf8mb4' NOT NULL,
  `MfaEnabled` TINYINT(1) NOT NULL DEFAULT 0,
  `MfaEnabledIp` VARBINARY(16) NULL DEFAULT NULL,
  `MfaEnabledUtc` DATETIME(6) NULL DEFAULT NULL,
  `MfaKey` VARCHAR(128) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `EmailVerified` TINYINT(1) NOT NULL DEFAULT 0,
  `EmailVerifiedIp` VARBINARY(16) NULL DEFAULT NULL,
  `EmailVerifiedUtc` DATETIME(6) NULL DEFAULT NULL,
  `EmailVerifyKey` VARCHAR(64) NULL DEFAULT NULL,
  `ForgotPassword` TINYINT(1) NOT NULL DEFAULT 0,
  `ForgotPasswordIp` VARBINARY(16) NULL DEFAULT NULL,
  `ForgotPasswordUtc` VARCHAR(64) NULL DEFAULT NULL,
  `ForgotPasswordKey` VARCHAR(64) NULL DEFAULT NULL,
  `ForgotPasswordExpiryUtc` DATETIME(6) NULL DEFAULT NULL,
  `ForgotResetIp` VARBINARY(16) NULL DEFAULT NULL,
  `ForgotResetUtc` DATETIME(6) NULL DEFAULT NULL,
  `LastLoginIp` VARBINARY(16) NULL DEFAULT NULL,
  `LastLoginUtc` DATETIME(6) NULL DEFAULT NULL,
  `FailedLogin` TINYINT(1) NOT NULL DEFAULT 0,
  `FailedLoginIp` VARBINARY(16) NULL DEFAULT NULL,
  `FailedLoginUtc` DATETIME(6) NULL DEFAULT NULL,
  `FailedLoginCount` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `CreatedIp` VARBINARY(16) NOT NULL,
  `CreatedUtc` DATETIME(6) NOT NULL,
  `Updated` TINYINT(1) NOT NULL DEFAULT 0,
  `UpdatedIp` VARBINARY(16) NULL DEFAULT NULL,
  `UpdatedUtc` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedUserId` BIGINT NULL DEFAULT NULL,
  `Deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `DeletedIp` VARBINARY(16) NULL DEFAULT NULL,
  `DeletedUtc` DATETIME(6) NULL DEFAULT NULL,
  `DeletedUserId` BIGINT NULL DEFAULT NULL,
  `CreatedUserId` BIGINT NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `UQ_Login_Key` (`Key` ASC) VISIBLE,
  UNIQUE INDEX `UQ_Login_Email` (`Email` ASC) VISIBLE,
  UNIQUE INDEX `IX_Composite_DeletedLogin` (`Email` ASC, `Password` ASC, `EmailVerified` ASC, `ForgotPassword` ASC, `Deleted` ASC, `FailedLoginCount` ASC) VISIBLE,
  UNIQUE INDEX `IX_Composite_Key` (`Key` ASC, `Password` ASC, `EmailVerified` ASC, `ForgotPassword` ASC, `Deleted` ASC, `FailedLoginCount` ASC) VISIBLE,
  INDEX `IX_DeletedUserId` (`DeletedUserId` ASC) VISIBLE,
  INDEX `IX_UpdatedUserId` (`UpdatedUserId` ASC) VISIBLE,
  CONSTRAINT `FK_Login_User_DeletedUserId`
    FOREIGN KEY (`DeletedUserId`)
    REFERENCES `CarClub`.`User` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Login_User_UpdatedUserId`
    FOREIGN KEY (`UpdatedUserId`)
    REFERENCES `CarClub`.`User` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `CarClub`.`Permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarClub`.`Permission` (
  `Id` BIGINT NOT NULL,
  `Code` VARCHAR(32) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `Title` VARCHAR(128) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `Note` VARCHAR(1024) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `CreatedIp` VARBINARY(16) NOT NULL,
  `CreatedUtc` DATETIME(6) NOT NULL,
  `CreatedUserId` BIGINT NOT NULL,
  `Updated` TINYINT(1) NOT NULL DEFAULT 0,
  `UpdatedIp` VARBINARY(16) NULL DEFAULT NULL,
  `UpdatedUtc` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedUserId` BIGINT NULL DEFAULT NULL,
  `Deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `DeletedIp` VARBINARY(16) NULL DEFAULT NULL,
  `DeletedUtc` DATETIME(6) NULL DEFAULT NULL,
  `DeletedUserId` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `IX_Composite` (`Id` ASC, `Code` ASC, `Title` ASC, `Deleted` ASC) VISIBLE,
  INDEX `IX_Composite_Code` (`Code` ASC, `Title` ASC, `Deleted` ASC) VISIBLE,
  INDEX `FK_Permission_User_DeletedUserId_idx` (`DeletedUserId` ASC) VISIBLE,
  INDEX `FK_Permission_User_CreatedUserId_idx` (`UpdatedUserId` ASC) VISIBLE,
  CONSTRAINT `FK_Permission_User_CreatedUserId`
    FOREIGN KEY (`UpdatedUserId`)
    REFERENCES `CarClub`.`User` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Permission_User_DeletedUserId`
    FOREIGN KEY (`DeletedUserId`)
    REFERENCES `CarClub`.`User` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Permission_User_UpdatedUserId`
    FOREIGN KEY (`UpdatedUserId`)
    REFERENCES `CarClub`.`User` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `CarClub`.`Role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarClub`.`Role` (
  `Id` BIGINT NOT NULL,
  `Code` VARCHAR(32) CHARACTER SET 'utf8mb4' NOT NULL,
  `Title` VARCHAR(128) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `Note` VARCHAR(1024) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `CreatedIp` VARBINARY(16) NOT NULL,
  `CreatedUtc` DATETIME(6) NOT NULL,
  `CreatedUserId` BIGINT NOT NULL,
  `Updated` TINYINT(1) NOT NULL DEFAULT 0,
  `UpdatedIp` VARBINARY(16) NULL DEFAULT NULL,
  `UpdatedUtc` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedUserId` BIGINT NULL DEFAULT NULL,
  `Deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `DeletedIp` VARBINARY(16) NULL DEFAULT NULL,
  `DeletedUtc` DATETIME(6) NULL DEFAULT NULL,
  `DeletedUserId` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `IX_Composite` (`Id` ASC, `Code` ASC, `Deleted` ASC) VISIBLE,
  CONSTRAINT `FK_Role_User_CreatedUserId`
    FOREIGN KEY ()
    REFERENCES `CarClub`.`User` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Role_User_DeletedUserId`
    FOREIGN KEY ()
    REFERENCES `CarClub`.`User` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Role_User_UpdatedUserId`
    FOREIGN KEY ()
    REFERENCES `CarClub`.`User` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `CarClub`.`RolePermission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarClub`.`RolePermission` (
  `Id` BIGINT NOT NULL,
  `RoleId` BIGINT NOT NULL,
  `PermissionId` BIGINT NOT NULL,
  `CreatedIp` VARBINARY(16) NOT NULL,
  `CreatedUtc` DATETIME(6) NOT NULL,
  `CreatedUserId` BIGINT NOT NULL,
  `Updated` TINYINT(1) NOT NULL DEFAULT 0,
  `UpdatedIp` VARBINARY(16) NULL DEFAULT NULL,
  `UpdatedUtc` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedUserId` BIGINT NULL DEFAULT NULL,
  `Deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `DeletedIp` VARBINARY(16) NULL DEFAULT NULL,
  `DeletedUtc` DATETIME(6) NULL DEFAULT NULL,
  `DeletedUserId` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `IX_RoleId` (`RoleId` ASC) VISIBLE,
  CONSTRAINT `FK_RolePermission_Permission_PermissionId`
    FOREIGN KEY ()
    REFERENCES `CarClub`.`Permission` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_RolePermission_Role_RoleId`
    FOREIGN KEY ()
    REFERENCES `CarClub`.`Role` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_RolePermission_User_CreatedUserId`
    FOREIGN KEY ()
    REFERENCES `CarClub`.`User` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_RolePermission_User_DeletedUserId`
    FOREIGN KEY ()
    REFERENCES `CarClub`.`User` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_RolePermission_User_UpdatedUserId`
    FOREIGN KEY ()
    REFERENCES `CarClub`.`User` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `CarClub`.`UserRole`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarClub`.`UserRole` (
  `Id` BIGINT NOT NULL,
  `UserId` BIGINT NOT NULL,
  `RoleId` BIGINT NOT NULL,
  `CreatedUtc` DATETIME(6) NOT NULL,
  `CreatedIp` VARBINARY(16) NOT NULL,
  `CreatedUserId` BIGINT NOT NULL,
  `Updated` TINYINT(1) NOT NULL DEFAULT 0,
  `UpdatedIp` VARBINARY(16) NULL DEFAULT NULL,
  `UpdatedUtc` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedUserId` BIGINT NULL DEFAULT NULL,
  `Deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `DeletedIp` VARBINARY(16) NULL DEFAULT NULL,
  `DeletedUtc` DATETIME(6) NULL DEFAULT NULL,
  `DeletedUserId` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `IX_Composite` (`UserId` ASC, `RoleId` ASC, `Deleted` ASC) INVISIBLE,
  INDEX `IX_UserId` (`UserId` ASC) INVISIBLE,
  INDEX `IX_RoleId` (`RoleId` ASC) INVISIBLE,
  INDEX `IX_CreatedUsedId` (`CreatedUserId` ASC) INVISIBLE,
  INDEX `IX_UpdatedUserId` (`UpdatedUserId` ASC) INVISIBLE,
  INDEX `IX_DeletedUserId` (`DeletedUserId` ASC) VISIBLE,
  CONSTRAINT `FK_UserRole_User_CreatedUserId`
    FOREIGN KEY ()
    REFERENCES `CarClub`.`User` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_UserRole_User_DeletedUserId`
    FOREIGN KEY ()
    REFERENCES `CarClub`.`User` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_UserRole_User_UpdatedUserId`
    FOREIGN KEY ()
    REFERENCES `CarClub`.`User` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_UserRole_User_UserId`
    FOREIGN KEY ()
    REFERENCES `CarClub`.`User` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_UserRole_Role_RoleId`
    FOREIGN KEY ()
    REFERENCES `CarClub`.`Role` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `CarClub`.`Board`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarClub`.`Board` (
  `Id` BIGINT NOT NULL,
  `Key` VARCHAR(64) NOT NULL,
  `Ordinal` INT NOT NULL,
  `Title` VARCHAR(128) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `Note` VARCHAR(1024) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `CreatedIp` VARBINARY(16) NOT NULL,
  `CreatedUtc` DATETIME(6) NOT NULL,
  `CreatedUserId` BIGINT NOT NULL,
  `UpdatedIp` VARBINARY(16) NULL DEFAULT NULL,
  `UpdatedUtc` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedUserId` BIGINT NULL DEFAULT NULL,
  `Deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `DeletedIp` VARBINARY(16) NULL DEFAULT NULL,
  `DeletedUtc` DATETIME(6) NULL DEFAULT NULL,
  `DeletedUserId` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `IX_Composite` (`Key` ASC, `Deleted` ASC) VISIBLE,
  CONSTRAINT `FK_Board_User_CreatedUserId`
    FOREIGN KEY ()
    REFERENCES `CarClub`.`User` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Board_User_UpdatedUserId`
    FOREIGN KEY ()
    REFERENCES `CarClub`.`User` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Board_User_DeletedUserId`
    FOREIGN KEY ()
    REFERENCES `CarClub`.`User` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `CarClub`.`BoardRolePermission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarClub`.`BoardRolePermission` (
  `Id` BIGINT NOT NULL,
  `BoardId` BIGINT NOT NULL,
  `RoleId` BIGINT NOT NULL,
  `PermissionId` BIGINT NOT NULL,
  `CreatedIp` VARBINARY(16) NOT NULL,
  `CreatedUtc` DATETIME(6) NOT NULL,
  `CreatedUserId` BIGINT NOT NULL,
  `Updated` TINYINT(1) NOT NULL DEFAULT 0,
  `UpdatedIp` VARBINARY(16) NULL DEFAULT NULL,
  `UpdatedUtc` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedUserId` BIGINT NULL DEFAULT NULL,
  `Deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `DeletedIp` VARBINARY(16) NULL DEFAULT NULL,
  `DeletedUtc` DATETIME(6) NULL DEFAULT NULL,
  `DeletedUserId` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `IX_Composite` (`Deleted` ASC, `BoardId` ASC, `RoleId` ASC, `PermissionId` ASC) VISIBLE,
  INDEX `FK_BoardRolePermission_Role_RoleId_idx` (`RoleId` ASC) VISIBLE,
  INDEX `FK_BoardRolePermission_Permission_PermissionId_idx` (`PermissionId` ASC) VISIBLE,
  INDEX `FK_BoardRolePermission_User_CreatedUserId_idx` (`CreatedUserId` ASC) VISIBLE,
  INDEX `FK_BoardRolePermission_User_UpdatedUserId_idx` (`UpdatedUserId` ASC) VISIBLE,
  INDEX `FK_BoardRolePermission_User_DeletedUserId_idx` (`DeletedUserId` ASC) VISIBLE,
  INDEX `FK_BoardRolePermission_Board_BoardId_idx` (`BoardId` ASC) VISIBLE,
  CONSTRAINT `FK_BoardRolePermission_Role_RoleId`
    FOREIGN KEY (`RoleId`)
    REFERENCES `CarClub`.`Role` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_BoardRolePermission_Permission_PermissionId`
    FOREIGN KEY (`PermissionId`)
    REFERENCES `CarClub`.`Permission` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_BoardRolePermission_User_CreatedUserId`
    FOREIGN KEY (`CreatedUserId`)
    REFERENCES `CarClub`.`User` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_BoardRolePermission_User_UpdatedUserId`
    FOREIGN KEY (`UpdatedUserId`)
    REFERENCES `CarClub`.`User` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_BoardRolePermission_User_DeletedUserId`
    FOREIGN KEY (`DeletedUserId`)
    REFERENCES `CarClub`.`User` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_BoardRolePermission_Board_BoardId`
    FOREIGN KEY (`BoardId`)
    REFERENCES `CarClub`.`Board` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `CarClub`.`BoardTag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarClub`.`BoardTag` (
  `Id` INT NOT NULL,
  `BoardId` BIGINT NULL,
  `TagId` BIGINT NULL,
  `CreatedIp` VARBINARY(16) NULL,
  `CreatedUtc` DATETIME(6) NULL,
  `CreatedUserId` BIGINT NOT NULL,
  `UpdatedIp` VARBINARY(16) NULL,
  `UpdatedUtc` DATETIME(6) NULL,
  `UpdatedUserId` BIGINT NULL,
  `DeletedIp` VARBINARY(16) NULL,
  `DeletedUtc` DATETIME(6) NULL,
  `DeletedUserId` BIGINT NULL,
  PRIMARY KEY (`Id`),
  INDEX `FK_BoardTag_Board_BoardId_idx` (`BoardId` ASC) VISIBLE,
  CONSTRAINT `FK_BoardTag_Board_BoardId`
    FOREIGN KEY (`BoardId`)
    REFERENCES `CarClub`.`Board` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `CarClub`.`Comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarClub`.`Comment` (
  `Id` BIGINT NOT NULL,
  `Key` VARCHAR(64) NOT NULL,
  `ParentId` BIGINT NULL DEFAULT NULL,
  `Title` VARCHAR(128) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `Content` VARCHAR(0) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `CreatedIp` VARBINARY(16) NOT NULL,
  `CreatedUtc` DATETIME(6) NOT NULL,
  `CreatedUserId` BIGINT NOT NULL,
  `Updated` TINYINT(1) NOT NULL DEFAULT 0,
  `UpdatedIp` VARBINARY(16) NULL DEFAULT NULL,
  `UpdatedUtc` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedUserId` BIGINT NULL DEFAULT NULL,
  `Deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `DeletedIp` VARBINARY(16) NULL DEFAULT NULL,
  `DeletedUtc` DATETIME(6) NULL DEFAULT NULL,
  `DeletedUserId` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `IX_Composite` (`Deleted` ASC, `ParentId` ASC) VISIBLE,
  INDEX `IX_Key` (`Key` ASC) VISIBLE,
  INDEX `IX_ParentId` (`ParentId` ASC) VISIBLE,
  CONSTRAINT `FK_Comment_Comment_ParentId`
    FOREIGN KEY (`ParentId`)
    REFERENCES `CarClub`.`Comment` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Comment_User_CreatedUserId`
    FOREIGN KEY ()
    REFERENCES `CarClub`.`User` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Comment_User_UpdatedUserId`
    FOREIGN KEY ()
    REFERENCES `CarClub`.`User` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Comment_User_DeletedUserId`
    FOREIGN KEY ()
    REFERENCES `CarClub`.`User` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `CarClub`.`CommentAttachment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarClub`.`CommentAttachment` (
  `Id` BIGINT NOT NULL,
  `CommentId` BIGINT NOT NULL,
  `Filename` VARCHAR(128) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `Url` VARCHAR(256) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `CreatedIp` VARBINARY(16) NOT NULL,
  `CreatedUtc` DATETIME(6) NOT NULL,
  `CreatedUserId` BIGINT NOT NULL,
  `Updated` TINYINT(1) NOT NULL DEFAULT 0,
  `UpdatedIp` VARBINARY(16) NULL DEFAULT NULL,
  `UpdatedUtc` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedUserId` BIGINT NULL DEFAULT NULL,
  `Deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `DeletedIp` VARBINARY(16) NULL DEFAULT NULL,
  `DeletedUtc` DATETIME(6) NULL DEFAULT NULL,
  `DeletedUserId` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `IX_Composite` (`Deleted` ASC, `CommentId` ASC, `Filename` ASC, `Url`(255) ASC) VISIBLE,
  INDEX `FK_CommentAttachment_User_CreatedUserId_idx` (`CreatedUserId` ASC) VISIBLE,
  INDEX `FK_CommentAttachment_User_UpdatedUserId_idx` (`UpdatedUserId` ASC) VISIBLE,
  INDEX `FK_CommentAttachment_User_DeletedUserId_idx` (`DeletedUserId` ASC) VISIBLE,
  INDEX `FK_CommentAttachment_Comment_CommentId_idx` (`CommentId` ASC) VISIBLE,
  CONSTRAINT `FK_CommentAttachment_User_CreatedUserId`
    FOREIGN KEY (`CreatedUserId`)
    REFERENCES `CarClub`.`User` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_CommentAttachment_User_UpdatedUserId`
    FOREIGN KEY (`UpdatedUserId`)
    REFERENCES `CarClub`.`User` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_CommentAttachment_User_DeletedUserId`
    FOREIGN KEY (`DeletedUserId`)
    REFERENCES `CarClub`.`User` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_CommentAttachment_Comment_CommentId`
    FOREIGN KEY (`CommentId`)
    REFERENCES `CarClub`.`Comment` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `CarClub`.`Member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarClub`.`Member` (
  `Id` BIGINT NOT NULL,
  `UserKey` VARCHAR(64) NULL DEFAULT NULL,
  `FullName` VARCHAR(256) CHARACTER SET 'utf8mb4' NOT NULL,
  `PreferredName` VARCHAR(128) CHARACTER SET 'utf8mb4' NOT NULL,
  `Phone` VARCHAR(16) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `Mobile` VARCHAR(16) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `Email` VARCHAR(128) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `PrimaryAddress_Street1` VARCHAR(128) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `PrimaryAddress_Street2` VARCHAR(128) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `PrimaryAddress_Suburb` VARCHAR(128) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `PrimaryAddress_Postcode` VARCHAR(8) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `PrimaryAddress_State` VARCHAR(32) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `PrimaryAddress_Latitude` DECIMAL(18,6) NULL DEFAULT NULL,
  `PrimaryAddress_Longitude` DECIMAL(18,6) NULL DEFAULT NULL,
  `CreatedIp` VARBINARY(16) NOT NULL,
  `CreatedUtc` DATETIME(6) NOT NULL,
  `CreatedUserId` BIGINT NOT NULL,
  `Updated` TINYINT(1) NOT NULL DEFAULT 0,
  `UpdatedIp` VARBINARY(16) NULL DEFAULT NULL,
  `UpdatedUtc` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedUserId` BIGINT NULL DEFAULT NULL,
  `Deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `DeletedIp` VARBINARY(16) NULL DEFAULT NULL,
  `DeletedUtc` DATETIME(6) NULL DEFAULT NULL,
  `DeletedUserId` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `IX_Key` (`UserKey` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `CarClub`.`CommentReaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarClub`.`CommentReaction` (
  `Id` BIGINT NOT NULL,
  `CommentId` BIGINT NOT NULL,
  `MemberId` BIGINT NOT NULL,
  `Emoji` CHAR(1) CHARACTER SET 'utf8mb4' NOT NULL,
  `CreatedIp` VARBINARY(16) NOT NULL,
  `CreatedUtc` DATETIME(6) NOT NULL,
  `CreatedUserId` BIGINT NOT NULL,
  `Updated` TINYINT(1) NOT NULL DEFAULT 0,
  `UpdatedIp` VARBINARY(16) NULL DEFAULT NULL,
  `UpdatedUtc` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedUserId` BIGINT NULL DEFAULT NULL,
  `Deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `DeletedIp` VARBINARY(16) NULL DEFAULT NULL,
  `DeletedUtc` DATETIME(6) NULL DEFAULT NULL,
  `DeletedUserId` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `IX_Composite` (`Deleted` ASC, `CommentId` ASC, `MemberId` ASC, `Emoji` ASC) VISIBLE,
  INDEX `FK_CommentReaction_User_CreatedUserId_idx` (`CreatedUserId` ASC) VISIBLE,
  INDEX `FK_CommentReaction_User_DeletedUserId_idx` (`DeletedUserId` ASC) VISIBLE,
  INDEX `FK_CommentReaction_Comment_CommentId_idx` (`CommentId` ASC) VISIBLE,
  INDEX `FK_CommentReaction_Member_idx` (`MemberId` ASC) VISIBLE,
  CONSTRAINT `FK_CommentReaction_User_CreatedUserId`
    FOREIGN KEY (`CreatedUserId`)
    REFERENCES `CarClub`.`User` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_CommentReaction_User_UpdatedUserId`
    FOREIGN KEY (`UpdatedUserId`)
    REFERENCES `CarClub`.`User` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_CommentReaction_User_DeletedUserId`
    FOREIGN KEY (`DeletedUserId`)
    REFERENCES `CarClub`.`User` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_CommentReaction_Comment_CommentId`
    FOREIGN KEY (`CommentId`)
    REFERENCES `CarClub`.`Comment` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_CommentReaction_Member`
    FOREIGN KEY (`MemberId`)
    REFERENCES `CarClub`.`Member` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `CarClub`.`Event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarClub`.`Event` (
  `Id` BIGINT NOT NULL,
  `MeetId` BIGINT NOT NULL,
  `StatusId` BIGINT NOT NULL,
  `Title` VARCHAR(256) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `Note` VARCHAR(1024) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `StartUtc` DATETIME(6) NULL DEFAULT NULL,
  `DurationMinutes` INT NULL DEFAULT NULL,
  `CreatedIp` VARBINARY(16) NOT NULL,
  `CreatedUtc` DATETIME(6) NOT NULL,
  `CreatedUserId` BIGINT NOT NULL,
  `Updated` TINYINT(1) NOT NULL DEFAULT 0,
  `UpdatedIp` VARBINARY(16) NULL DEFAULT NULL,
  `UpdatedUtc` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedUserId` BIGINT NULL DEFAULT NULL,
  `Deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `DeletedIp` VARBINARY(16) NULL DEFAULT NULL,
  `DeletedUtc` DATETIME(6) NULL DEFAULT NULL,
  `DeletedUserId` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `FK_Event_User_CreatedUserId` (`CreatedUserId` ASC) VISIBLE,
  INDEX `FK_Event_User_UpdatedUserId` (`UpdatedUserId` ASC) VISIBLE,
  INDEX `FK_Event_User_DeletedUserId` (`DeletedUserId` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `CarClub`.`EventAttachment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarClub`.`EventAttachment` (
  `Id` BIGINT NOT NULL,
  `EventId` BIGINT NOT NULL,
  `Title` VARCHAR(256) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `Filename` VARCHAR(128) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `Url` VARCHAR(256) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `CreatedIp` VARBINARY(16) NOT NULL,
  `CreatedUtc` DATETIME(6) NOT NULL,
  `CreatedUserId` BIGINT NOT NULL,
  `Updated` TINYINT(1) NOT NULL DEFAULT 0,
  `UpdatedIp` VARBINARY(16) NULL DEFAULT NULL,
  `UpdatedUtc` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedUserId` BIGINT NULL DEFAULT NULL,
  `Deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `DeletedIp` VARBINARY(16) NULL DEFAULT NULL,
  `DeletedUtc` DATETIME(6) NULL DEFAULT NULL,
  `DeletedUserId` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `FK_EventAttachment_User_CreatedUserId` (`CreatedUserId` ASC) VISIBLE,
  INDEX `FK_EventAttachment_User_UpdatedUserId` (`UpdatedUserId` ASC) VISIBLE,
  INDEX `FK_EventAttachment_User_DeletedUserId` (`DeletedUserId` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `CarClub`.`EventMemberRole`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarClub`.`EventMemberRole` (
  `Id` BIGINT NOT NULL,
  `EventId` BIGINT NOT NULL,
  `MemberId` BIGINT NOT NULL,
  `RoleId` BIGINT NOT NULL,
  `CreatedIp` VARBINARY(16) NOT NULL,
  `CreatedUtc` DATETIME(6) NOT NULL,
  `CreatedUserId` BIGINT NOT NULL,
  `Updated` TINYINT(1) NOT NULL DEFAULT 0,
  `UpdatedIp` VARBINARY(16) NULL DEFAULT NULL,
  `UpdatedUtc` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedUserId` BIGINT NULL DEFAULT NULL,
  `Deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `DeletedIp` VARBINARY(16) NULL DEFAULT NULL,
  `DeletedUtc` DATETIME(6) NULL DEFAULT NULL,
  `DeletedUserId` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `FK_EventMemberRole_User_CreatedUserId` (`CreatedUserId` ASC) VISIBLE,
  INDEX `FK_EventMemberRole_User_UpdatedUserId` (`UpdatedUserId` ASC) VISIBLE,
  INDEX `FK_EventMemberRole_User_DeletedUserId` (`DeletedUserId` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `CarClub`.`EventReaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarClub`.`EventReaction` (
  `Id` BIGINT NOT NULL,
  `EventId` BIGINT NOT NULL,
  `MemberId` BIGINT NOT NULL,
  `ReactionId` BIGINT NOT NULL,
  `Emoji` CHAR(1) CHARACTER SET 'utf8mb4' NOT NULL,
  `CreatedIp` VARBINARY(16) NOT NULL,
  `CreatedUtc` DATETIME(6) NOT NULL,
  `CreatedUserId` BIGINT NOT NULL,
  `Updated` TINYINT(1) NOT NULL DEFAULT 0,
  `UpdatedIp` VARBINARY(16) NULL DEFAULT NULL,
  `UpdatedUtc` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedUserId` BIGINT NULL DEFAULT NULL,
  `Deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `DeletedIp` VARBINARY(16) NULL DEFAULT NULL,
  `DeletedUtc` DATETIME(6) NULL DEFAULT NULL,
  `DeletedUserId` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `IX_Reaction` (`ReactionId` ASC) VISIBLE,
  INDEX `FK_EventReaction_User_CreatedUserId` (`CreatedUserId` ASC) VISIBLE,
  INDEX `FK_EventReaction_User_UpdatedUserId` (`UpdatedUserId` ASC) VISIBLE,
  INDEX `FK_EventReaction_User_DeletedUserId` (`DeletedUserId` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `CarClub`.`EventStatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarClub`.`EventStatus` (
  `Id` BIGINT NOT NULL,
  `Code` VARCHAR(32) CHARACTER SET 'utf8mb4' NOT NULL,
  `Title` VARCHAR(128) CHARACTER SET 'utf8mb4' NOT NULL,
  `Note` VARCHAR(1024) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `CreatedIp` VARBINARY(16) NOT NULL,
  `CreatedUtc` DATETIME(6) NOT NULL,
  `CreatedUserId` BIGINT NOT NULL,
  `Updated` TINYINT(1) NOT NULL DEFAULT 0,
  `UpdatedIp` VARBINARY(16) NULL DEFAULT NULL,
  `UpdatedUtc` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedUserId` BIGINT NULL DEFAULT NULL,
  `Deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `DeletedIp` VARBINARY(16) NULL DEFAULT NULL,
  `DeletedUtc` DATETIME(6) NULL DEFAULT NULL,
  `DeletedUserId` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `FK_EventStatus_User_CreatedUserId` (`CreatedUserId` ASC) VISIBLE,
  INDEX `FK_EventStatus_User_UpdatedUserId` (`UpdatedUserId` ASC) VISIBLE,
  INDEX `FK_EventStatus_User_DeletedUserId` (`DeletedUserId` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `CarClub`.`EventTag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarClub`.`EventTag` (
  `Id` BIGINT NOT NULL,
  `Code` VARCHAR(32) CHARACTER SET 'utf8mb4' NOT NULL,
  `Title` VARCHAR(128) CHARACTER SET 'utf8mb4' NOT NULL,
  `Note` VARCHAR(1024) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `CreatedIp` VARBINARY(16) NOT NULL,
  `CreatedUtc` DATETIME(6) NOT NULL,
  `CreatedUserId` BIGINT NOT NULL,
  `Updated` TINYINT(1) NOT NULL DEFAULT 0,
  `UpdatedIp` VARBINARY(16) NULL DEFAULT NULL,
  `UpdatedUtc` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedUserId` BIGINT NULL DEFAULT NULL,
  `Deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `DeletedIp` VARBINARY(16) NULL DEFAULT NULL,
  `DeletedUtc` DATETIME(6) NULL DEFAULT NULL,
  `DeletedUserId` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `FK_EventTag_User_CreatedUserId` (`CreatedUserId` ASC) VISIBLE,
  INDEX `FK_EventTag_User_UpdatedUserId` (`UpdatedUserId` ASC) VISIBLE,
  INDEX `FK_EventTag_User_DeletedUserId` (`DeletedUserId` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `CarClub`.`Grid`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarClub`.`Grid` (
  `Id` BIGINT NOT NULL,
  `HeatId` BIGINT NOT NULL,
  `MemberId` BIGINT NULL DEFAULT NULL,
  `VehicleId` BIGINT NULL DEFAULT NULL,
  `Position` INT NULL DEFAULT NULL,
  `CreatedIp` VARBINARY(16) NOT NULL,
  `CreatedUtc` DATETIME(6) NOT NULL,
  `CreatedUserId` BIGINT NOT NULL,
  `Updated` TINYINT(1) NOT NULL DEFAULT 0,
  `UpdatedIp` VARBINARY(16) NULL DEFAULT NULL,
  `UpdatedUtc` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedUserId` BIGINT NULL DEFAULT NULL,
  `Deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `DeletedIp` VARBINARY(16) NULL DEFAULT NULL,
  `DeletedUtc` DATETIME(6) NULL DEFAULT NULL,
  `DeletedUserId` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `IX_DriverId` (`MemberId` ASC) VISIBLE,
  INDEX `IX_Vehicle` (`VehicleId` ASC) VISIBLE,
  INDEX `FK_Grid_User_CreatedUserId` (`CreatedUserId` ASC) VISIBLE,
  INDEX `FK_Grid_User_UpdatedUserId` (`UpdatedUserId` ASC) VISIBLE,
  INDEX `FK_Grid_User_DeletedUserId` (`DeletedUserId` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `CarClub`.`GridReaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarClub`.`GridReaction` (
  `Id` BIGINT NOT NULL,
  `GridId` BIGINT NOT NULL,
  `MemberId` BIGINT NOT NULL,
  `Emoji` CHAR(1) CHARACTER SET 'utf8mb4' NOT NULL,
  `CreatedIp` VARBINARY(16) NOT NULL,
  `CreatedUtc` DATETIME(6) NOT NULL,
  `CreatedUserId` BIGINT NOT NULL,
  `Updated` TINYINT(1) NOT NULL DEFAULT 0,
  `UpdatedIp` VARBINARY(16) NULL DEFAULT NULL,
  `UpdatedUtc` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedUserId` BIGINT NULL DEFAULT NULL,
  `Deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `DeletedIp` VARBINARY(16) NULL DEFAULT NULL,
  `DeletedUtc` DATETIME(6) NULL DEFAULT NULL,
  `DeletedUserId` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `FK_GridReaction_User_CreatedUserId` (`CreatedUserId` ASC) VISIBLE,
  INDEX `FK_GridReaction_User_UpdatedUserId` (`UpdatedUserId` ASC) VISIBLE,
  INDEX `FK_GridReaction_User_DeletedUserId` (`DeletedUserId` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `CarClub`.`Heat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarClub`.`Heat` (
  `Id` BIGINT NOT NULL,
  `EventId` BIGINT NOT NULL,
  `StatusId` BIGINT NULL DEFAULT NULL,
  `Code` VARCHAR(32) CHARACTER SET 'utf8mb4' NOT NULL,
  `Title` VARCHAR(128) CHARACTER SET 'utf8mb4' NOT NULL,
  `Note` VARCHAR(1024) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `CreatedIp` VARBINARY(16) NOT NULL,
  `CreatedUtc` DATETIME(6) NOT NULL,
  `CreatedUserId` BIGINT NOT NULL,
  `Updated` TINYINT(1) NOT NULL DEFAULT 0,
  `UpdatedIp` VARBINARY(16) NULL DEFAULT NULL,
  `UpdatedUtc` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedUserId` BIGINT NULL DEFAULT NULL,
  `Deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `DeletedIp` VARBINARY(16) NULL DEFAULT NULL,
  `DeletedUtc` DATETIME(6) NULL DEFAULT NULL,
  `DeletedUserId` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `FK_Heat_User_CreatedUserId` (`CreatedUserId` ASC) VISIBLE,
  INDEX `FK_Heat_User_UpdatedUserId` (`UpdatedUserId` ASC) VISIBLE,
  INDEX `FK_Heat_User_DeletedUserId` (`DeletedUserId` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `CarClub`.`HeatAttachment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarClub`.`HeatAttachment` (
  `Id` BIGINT NOT NULL,
  `HeatId` BIGINT NOT NULL,
  `UploadIp` VARCHAR(16) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `UploadUtc` DATETIME(6) NULL DEFAULT NULL,
  `Title` VARCHAR(256) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `Filename` VARCHAR(128) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `Url` VARCHAR(256) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `CreatedIp` VARBINARY(16) NOT NULL,
  `CreatedUtc` DATETIME(6) NOT NULL,
  `CreatedUserId` BIGINT NOT NULL,
  `Updated` TINYINT(1) NOT NULL DEFAULT 0,
  `UpdatedIp` VARBINARY(16) NULL DEFAULT NULL,
  `UpdatedUtc` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedUserId` BIGINT NULL DEFAULT NULL,
  `Deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `DeletedIp` VARBINARY(16) NULL DEFAULT NULL,
  `DeletedUtc` DATETIME(6) NULL DEFAULT NULL,
  `DeletedUserId` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `FK_HeatAttachment_User_CreatedUserId` (`CreatedUserId` ASC) VISIBLE,
  INDEX `FK_HeatAttachment_User_UpdatedUserId` (`UpdatedUserId` ASC) VISIBLE,
  INDEX `FK_HeatAttachment_User_DeletedUserId` (`DeletedUserId` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `CarClub`.`HeatPenaltyStatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarClub`.`HeatPenaltyStatus` (
  `Id` BIGINT NOT NULL,
  `Code` VARCHAR(32) CHARACTER SET 'utf8mb4' NOT NULL,
  `Title` VARCHAR(128) CHARACTER SET 'utf8mb4' NOT NULL,
  `Note` VARCHAR(1024) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `CreatedIp` VARBINARY(16) NOT NULL,
  `CreatedUtc` DATETIME(6) NOT NULL,
  `CreatedUserId` BIGINT NOT NULL,
  `Updated` TINYINT(1) NOT NULL DEFAULT 0,
  `UpdatedIp` VARBINARY(16) NULL DEFAULT NULL,
  `UpdatedUtc` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedUserId` BIGINT NULL DEFAULT NULL,
  `Deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `DeletedIp` VARBINARY(16) NULL DEFAULT NULL,
  `DeletedUtc` DATETIME(6) NULL DEFAULT NULL,
  `DeletedUserId` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`));


-- -----------------------------------------------------
-- Table `CarClub`.`HeatReaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarClub`.`HeatReaction` (
  `Id` BIGINT NOT NULL,
  `HeatId` BIGINT NOT NULL,
  `MemberId` BIGINT NOT NULL,
  `Emoji` CHAR(1) CHARACTER SET 'utf8mb4' NOT NULL,
  `CreatedIp` VARBINARY(16) NOT NULL,
  `CreatedUtc` DATETIME(6) NOT NULL,
  `CreatedUserId` BIGINT NOT NULL,
  `Updated` TINYINT(1) NOT NULL DEFAULT 0,
  `UpdatedIp` VARBINARY(16) NULL DEFAULT NULL,
  `UpdatedUtc` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedUserId` BIGINT NULL DEFAULT NULL,
  `Deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `DeletedIp` VARBINARY(16) NULL DEFAULT NULL,
  `DeletedUtc` DATETIME(6) NULL DEFAULT NULL,
  `DeletedUserId` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `FK_HeatReaction_User_CreatedUserId` (`CreatedUserId` ASC) VISIBLE,
  INDEX `FK_HeatReaction_User_UpdatedUserId` (`UpdatedUserId` ASC) VISIBLE,
  INDEX `FK_HeatReaction_User_DeletedUserId` (`DeletedUserId` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `CarClub`.`HeatStatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarClub`.`HeatStatus` (
  `Id` BIGINT NOT NULL,
  `Code` VARCHAR(32) CHARACTER SET 'utf8mb4' NOT NULL,
  `Title` VARCHAR(128) CHARACTER SET 'utf8mb4' NOT NULL,
  `Note` VARCHAR(1024) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `CreatedIp` VARBINARY(16) NOT NULL,
  `CreatedUtc` DATETIME(6) NOT NULL,
  `CreatedUserId` BIGINT NOT NULL,
  `Updated` TINYINT(1) NOT NULL DEFAULT 0,
  `UpdatedIp` VARBINARY(16) NULL DEFAULT NULL,
  `UpdatedUtc` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedUserId` BIGINT NULL DEFAULT NULL,
  `Deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `DeletedIp` VARBINARY(16) NULL DEFAULT NULL,
  `DeletedUtc` DATETIME(6) NULL DEFAULT NULL,
  `DeletedUserId` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `IX_Composite` (`Deleted` ASC, `Code` ASC, `Title` ASC, `Updated` ASC) VISIBLE,
  INDEX `FK_HeatStatus_User_CreatedUserId` (`CreatedUserId` ASC) VISIBLE,
  INDEX `FK_HeatStatus_User_UpdatedUserId` (`UpdatedUserId` ASC) VISIBLE,
  INDEX `FK_HeatStatus_User_DeletedUserId` (`DeletedUserId` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `CarClub`.`HeatTag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarClub`.`HeatTag` (
  `Id` BIGINT NOT NULL,
  `HeatId` BIGINT NOT NULL,
  `TagId` BIGINT NOT NULL,
  `CreatedIp` VARBINARY(16) NOT NULL,
  `CreatedUtc` DATETIME(6) NOT NULL,
  `CreatedUserId` BIGINT NOT NULL,
  `Updated` TINYINT(1) NOT NULL DEFAULT 0,
  `UpdatedIp` VARBINARY(16) NULL DEFAULT NULL,
  `UpdatedUtc` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedUserId` BIGINT NULL DEFAULT NULL,
  `Deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `DeletedIp` VARBINARY(16) NULL DEFAULT NULL,
  `DeletedUtc` DATETIME(6) NULL DEFAULT NULL,
  `DeletedUserId` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `FK_HeatTag_User_CreatedUserId` (`CreatedUserId` ASC) VISIBLE,
  INDEX `FK_HeatTag_User_UpdatedUserId` (`UpdatedUserId` ASC) VISIBLE,
  INDEX `FK_HeatTag_User_DeletedUserId` (`DeletedUserId` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `CarClub`.`Invoice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarClub`.`Invoice` (
  `Id` BIGINT NOT NULL,
  `CustomerId` BIGINT NOT NULL,
  `StatusId` BIGINT NOT NULL,
  `Note` VARCHAR(1024) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `CreatedIp` VARBINARY(16) NOT NULL,
  `CreatedUtc` DATETIME(6) NOT NULL,
  `CreatedUserId` BIGINT NOT NULL,
  `Updated` TINYINT(1) NOT NULL DEFAULT 0,
  `UpdatedIp` VARBINARY(16) NULL DEFAULT NULL,
  `UpdatedUtc` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedUserId` BIGINT NULL DEFAULT NULL,
  `Deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `DeletedIp` VARBINARY(16) NULL DEFAULT NULL,
  `DeletedUtc` DATETIME(6) NULL DEFAULT NULL,
  `DeletedUserId` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `FK_Invoice_User_CreatedUserId` (`CreatedUserId` ASC) VISIBLE,
  INDEX `FK_Invoice_User_UpdatedUserId` (`UpdatedUserId` ASC) VISIBLE,
  INDEX `FK_Invoice_User_DeletedUserId` (`DeletedUserId` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `CarClub`.`InvoiceDetail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarClub`.`InvoiceDetail` (
  `Id` BIGINT NOT NULL,
  `StockId` BIGINT NOT NULL,
  `Quantity` DECIMAL(18,6) NOT NULL,
  `Note` VARCHAR(1024) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `CreatedIp` VARBINARY(16) NOT NULL,
  `CreatedUtc` DATETIME(6) NOT NULL,
  `CreatedUserId` BIGINT NOT NULL,
  `Updated` TINYINT(1) NOT NULL DEFAULT 0,
  `UpdatedIp` VARBINARY(16) NULL DEFAULT NULL,
  `UpdatedUtc` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedUserId` BIGINT NULL DEFAULT NULL,
  `Deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `DeletedIp` VARBINARY(16) NULL DEFAULT NULL,
  `DeletedUtc` DATETIME(6) NULL DEFAULT NULL,
  `DeletedUserId` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `IX_Composite` (`Deleted` ASC, `StockId` ASC, `Quantity` ASC, `Updated` ASC) VISIBLE,
  INDEX `FK_InvoiceDetail_User_CreatedUserId` (`CreatedUserId` ASC) VISIBLE,
  INDEX `FK_InvoiceDetail_User_UpdatedUserId` (`UpdatedUserId` ASC) VISIBLE,
  INDEX `FK_InvoiceDetail_User_DeletedUserId` (`DeletedUserId` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `CarClub`.`InvoiceStatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarClub`.`InvoiceStatus` (
  `Id` BIGINT NOT NULL,
  `Code` VARCHAR(32) CHARACTER SET 'utf8mb4' NOT NULL,
  `Title` VARCHAR(128) CHARACTER SET 'utf8mb4' NOT NULL,
  `Note` VARCHAR(1024) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `CreatedIp` VARBINARY(16) NOT NULL,
  `CreatedUtc` DATETIME(6) NOT NULL,
  `CreatedUserId` BIGINT NOT NULL,
  `Updated` TINYINT(1) NOT NULL DEFAULT 0,
  `UpdatedIp` VARBINARY(16) NULL DEFAULT NULL,
  `UpdatedUtc` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedUserId` BIGINT NULL DEFAULT NULL,
  `Deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `DeletedIp` VARBINARY(16) NULL DEFAULT NULL,
  `DeletedUtc` DATETIME(6) NULL DEFAULT NULL,
  `DeletedUserId` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `IX_Composite` (`Deleted` ASC, `Code` ASC, `Title` ASC, `Updated` ASC) VISIBLE,
  INDEX `FK_InvoiceStatus_User_CreatedUserId` (`CreatedUserId` ASC) VISIBLE,
  INDEX `FK_InvoiceStatus_User_UpdatedUserId` (`UpdatedUserId` ASC) VISIBLE,
  INDEX `FK_InvoiceStatus_User_DeletedUserId` (`DeletedUserId` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `CarClub`.`Lap`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarClub`.`Lap` (
  `Id` BIGINT NOT NULL,
  `HeatId` BIGINT NOT NULL,
  `VehicleId` BIGINT NULL DEFAULT NULL,
  `DriverId` BIGINT NULL DEFAULT NULL,
  `StatusId` BIGINT NULL DEFAULT NULL,
  `StartTime` TINYINT(1) NOT NULL DEFAULT 0,
  `StartTimeMs` DECIMAL(18,6) NULL DEFAULT NULL,
  `StartTimeIp` VARBINARY(16) NOT NULL,
  `StartTimeUtc` DATETIME(6) NOT NULL,
  `StartTimeBy` VARCHAR(128) CHARACTER SET 'utf8mb4' NOT NULL,
  `EndTime` TINYINT(1) NOT NULL DEFAULT 0,
  `EndTimeMs` DECIMAL(18,6) NULL DEFAULT NULL,
  `EndTimeIp` VARBINARY(16) NOT NULL,
  `EndTimeUtc` DATETIME(6) NOT NULL,
  `EndTimeBy` VARCHAR(128) CHARACTER SET 'utf8mb4' NOT NULL,
  `Time` TINYINT(1) NOT NULL DEFAULT 0,
  `TimeMs` DECIMAL(18,6) NULL DEFAULT NULL,
  `TimeIp` VARBINARY(16) NOT NULL,
  `TimeUtc` DATETIME(6) NOT NULL,
  `TimeBy` VARCHAR(128) CHARACTER SET 'utf8mb4' NOT NULL,
  `Position` TINYINT(1) NOT NULL DEFAULT 0,
  `PositionNumber` TINYINT UNSIGNED NULL DEFAULT NULL,
  `PositionIp` VARBINARY(16) NOT NULL,
  `PositionUtc` DATETIME(6) NOT NULL,
  `PositionBy` VARCHAR(128) CHARACTER SET 'utf8mb4' NOT NULL,
  `CreatedIp` VARBINARY(16) NOT NULL,
  `CreatedUtc` DATETIME(6) NOT NULL,
  `CreatedUserId` BIGINT NOT NULL,
  `Updated` TINYINT(1) NOT NULL DEFAULT 0,
  `UpdatedIp` VARBINARY(16) NULL DEFAULT NULL,
  `UpdatedUtc` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedUserId` BIGINT NULL DEFAULT NULL,
  `Deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `DeletedIp` VARBINARY(16) NULL DEFAULT NULL,
  `DeletedUtc` DATETIME(6) NULL DEFAULT NULL,
  `DeletedUserId` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `FK_Lap_User_CreatedUserId` (`CreatedUserId` ASC) VISIBLE,
  INDEX `FK_Lap_User_UpdatedUserId` (`UpdatedUserId` ASC) VISIBLE,
  INDEX `FK_Lap_User_DeletedUserId` (`DeletedUserId` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `CarClub`.`LapReaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarClub`.`LapReaction` (
  `Id` BIGINT NOT NULL,
  `LapId` BIGINT NOT NULL,
  `MemberId` BIGINT NOT NULL,
  `Emoji` CHAR(1) CHARACTER SET 'utf8mb4' NOT NULL,
  `CreatedIp` VARBINARY(16) NOT NULL,
  `CreatedUtc` DATETIME(6) NOT NULL,
  `CreatedUserId` BIGINT NOT NULL,
  `Updated` TINYINT(1) NOT NULL DEFAULT 0,
  `UpdatedIp` VARBINARY(16) NULL DEFAULT NULL,
  `UpdatedUtc` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedUserId` BIGINT NULL DEFAULT NULL,
  `Deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `DeletedIp` VARBINARY(16) NULL DEFAULT NULL,
  `DeletedUtc` DATETIME(6) NULL DEFAULT NULL,
  `DeletedUserId` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `FK_LapReaction_User_CreatedUserId` (`CreatedUserId` ASC) VISIBLE,
  INDEX `FK_LapReaction_User_UpdatedUserId` (`UpdatedUserId` ASC) VISIBLE,
  INDEX `FK_LapReaction_User_DeletedUserId` (`DeletedUserId` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `CarClub`.`LapStatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarClub`.`LapStatus` (
  `Id` BIGINT NOT NULL,
  `Code` VARCHAR(32) CHARACTER SET 'utf8mb4' NOT NULL,
  `Title` VARCHAR(128) CHARACTER SET 'utf8mb4' NOT NULL,
  `Note` VARCHAR(1024) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `CreatedIp` VARBINARY(16) NOT NULL,
  `CreatedUtc` DATETIME(6) NOT NULL,
  `CreatedUserId` BIGINT NOT NULL,
  `Updated` TINYINT(1) NOT NULL DEFAULT 0,
  `UpdatedIp` VARBINARY(16) NULL DEFAULT NULL,
  `UpdatedUtc` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedUserId` BIGINT NULL DEFAULT NULL,
  `Deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `DeletedIp` VARBINARY(16) NULL DEFAULT NULL,
  `DeletedUtc` DATETIME(6) NULL DEFAULT NULL,
  `DeletedUserId` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `IX_Composite` (`Deleted` ASC, `Code` ASC, `Title` ASC, `Updated` ASC) VISIBLE,
  INDEX `FK_LapStatus_User_CreatedUserId` (`CreatedUserId` ASC) VISIBLE,
  INDEX `FK_LapStatus_User_UpdatedUserId` (`UpdatedUserId` ASC) VISIBLE,
  INDEX `FK_LapStatus_User_DeletedUserId` (`DeletedUserId` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `CarClub`.`LapTag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarClub`.`LapTag` (
  `Id` BIGINT NOT NULL,
  `Code` VARCHAR(32) CHARACTER SET 'utf8mb4' NOT NULL,
  `Title` VARCHAR(128) CHARACTER SET 'utf8mb4' NOT NULL,
  `Note` VARCHAR(1024) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `CreatedIp` VARBINARY(16) NOT NULL,
  `CreatedUtc` DATETIME(6) NOT NULL,
  `CreatedUserId` BIGINT NOT NULL,
  `Updated` TINYINT(1) NOT NULL DEFAULT 0,
  `UpdatedIp` VARBINARY(16) NULL DEFAULT NULL,
  `UpdatedUtc` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedUserId` BIGINT NULL DEFAULT NULL,
  `Deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `DeletedIp` VARBINARY(16) NULL DEFAULT NULL,
  `DeletedUtc` DATETIME(6) NULL DEFAULT NULL,
  `DeletedUserId` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `FK_LapTag_User_CreatedUserId` (`CreatedUserId` ASC) VISIBLE,
  INDEX `FK_LapTag_User_UpdatedUserId` (`UpdatedUserId` ASC) VISIBLE,
  INDEX `FK_LapTag_User_DeletedUserId` (`DeletedUserId` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `CarClub`.`Meet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarClub`.`Meet` (
  `Id` BIGINT NOT NULL,
  `MeetStatusId` BIGINT NOT NULL,
  `StartUtc` DATETIME(6) NULL DEFAULT NULL,
  `DurationMinutes` INT NULL DEFAULT NULL,
  `Title` VARCHAR(128) CHARACTER SET 'utf8mb4' NOT NULL,
  `Note` VARCHAR(1024) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `CreatedIp` VARBINARY(16) NOT NULL,
  `CreatedUtc` DATETIME(6) NOT NULL,
  `CreatedUserId` BIGINT NOT NULL,
  `Updated` TINYINT(1) NOT NULL DEFAULT 0,
  `UpdatedIp` VARBINARY(16) NULL DEFAULT NULL,
  `UpdatedUtc` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedUserId` BIGINT NULL DEFAULT NULL,
  `Deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `DeletedIp` VARBINARY(16) NULL DEFAULT NULL,
  `DeletedUtc` DATETIME(6) NULL DEFAULT NULL,
  `DeletedUserId` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `FK_Meet_User_CreatedUserId` (`CreatedUserId` ASC) VISIBLE,
  INDEX `FK_Meet_User_UpdatedUserId` (`UpdatedUserId` ASC) VISIBLE,
  INDEX `FK_Meet_User_DeletedUserId` (`DeletedUserId` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `CarClub`.`MeetAttachment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarClub`.`MeetAttachment` (
  `Id` BIGINT NOT NULL,
  `MeetId` BIGINT NOT NULL,
  `Title` VARCHAR(256) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `Filename` VARCHAR(128) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `Url` VARCHAR(256) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `CreatedIp` VARBINARY(16) NOT NULL,
  `CreatedUtc` DATETIME(6) NOT NULL,
  `CreatedUserId` BIGINT NOT NULL,
  `Updated` TINYINT(1) NOT NULL DEFAULT 0,
  `UpdatedIp` VARBINARY(16) NULL DEFAULT NULL,
  `UpdatedUtc` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedUserId` BIGINT NULL DEFAULT NULL,
  `Deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `DeletedIp` VARBINARY(16) NULL DEFAULT NULL,
  `DeletedUtc` DATETIME(6) NULL DEFAULT NULL,
  `DeletedUserId` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `FK_MeetAttachment_User_CreatedUserId` (`CreatedUserId` ASC) VISIBLE,
  INDEX `FK_MeetAttachment_User_UpdatedUserId` (`UpdatedUserId` ASC) VISIBLE,
  INDEX `FK_MeetAttachment_User_DeletedUserId` (`DeletedUserId` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `CarClub`.`MeetOfficial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarClub`.`MeetOfficial` (
  `Id` BIGINT NOT NULL,
  `MeetId` BIGINT NOT NULL,
  `OfficeId` BIGINT NOT NULL,
  `MemberId` BIGINT NOT NULL,
  `CreatedIp` VARBINARY(16) NOT NULL,
  `CreatedUtc` DATETIME(6) NOT NULL,
  `CreatedUserId` BIGINT NOT NULL,
  `Updated` TINYINT(1) NOT NULL DEFAULT 0,
  `UpdatedIp` VARBINARY(16) NULL DEFAULT NULL,
  `UpdatedUtc` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedUserId` BIGINT NULL DEFAULT NULL,
  `Deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `DeletedIp` VARBINARY(16) NULL DEFAULT NULL,
  `DeletedUtc` DATETIME(6) NULL DEFAULT NULL,
  `DeletedUserId` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `FK_MeetOfficial_User_CreatedUserId` (`CreatedUserId` ASC) VISIBLE,
  INDEX `FK_MeetOfficial_User_UpdatedUserId` (`UpdatedUserId` ASC) VISIBLE,
  INDEX `FK_MeetOfficial_User_DeletedUserId` (`DeletedUserId` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `CarClub`.`MeetReaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarClub`.`MeetReaction` (
  `Id` BIGINT NOT NULL,
  `MeetId` BIGINT NOT NULL,
  `MemberId` BIGINT NOT NULL,
  `Emoji` CHAR(1) CHARACTER SET 'utf8mb4' NOT NULL,
  `CreatedIp` VARBINARY(16) NOT NULL,
  `CreatedUtc` DATETIME(6) NOT NULL,
  `CreatedUserId` BIGINT NOT NULL,
  `Updated` TINYINT(1) NOT NULL DEFAULT 0,
  `UpdatedIp` VARBINARY(16) NULL DEFAULT NULL,
  `UpdatedUtc` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedUserId` BIGINT NULL DEFAULT NULL,
  `Deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `DeletedIp` VARBINARY(16) NULL DEFAULT NULL,
  `DeletedUtc` DATETIME(6) NULL DEFAULT NULL,
  `DeletedUserId` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `FK_MeetReaction_User_CreatedUserId` (`CreatedUserId` ASC) VISIBLE,
  INDEX `FK_MeetReaction_User_UpdatedUserId` (`UpdatedUserId` ASC) VISIBLE,
  INDEX `FK_MeetReaction_User_DeletedUserId` (`DeletedUserId` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `CarClub`.`MeetStatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarClub`.`MeetStatus` (
  `Id` BIGINT NOT NULL,
  `Code` VARCHAR(32) CHARACTER SET 'utf8mb4' NOT NULL,
  `Title` VARCHAR(128) CHARACTER SET 'utf8mb4' NOT NULL,
  `Note` VARCHAR(1024) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `CreatedUtc` DATETIME(6) NOT NULL,
  `CreatedIp` VARBINARY(16) NOT NULL,
  `CreatedUserId` BIGINT NOT NULL,
  `Updated` TINYINT(1) NOT NULL DEFAULT 0,
  `UpdatedIp` VARBINARY(16) NULL DEFAULT NULL,
  `UpdatedUtc` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedUserId` BIGINT NULL DEFAULT NULL,
  `Deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `DeletedIp` VARBINARY(16) NULL DEFAULT NULL,
  `DeletedUtc` DATETIME(6) NULL DEFAULT NULL,
  `DeletedUserId` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `IX_Composite` (`Deleted` ASC, `Code` ASC, `Title` ASC, `Updated` ASC) VISIBLE,
  INDEX `FK_MeetStatus_User_CreatedUserId` (`CreatedUserId` ASC) VISIBLE,
  INDEX `FK_MeetStatus_User_UpdatedUserId` (`UpdatedUserId` ASC) VISIBLE,
  INDEX `FK_MeetStatus_User_DeletedUserId` (`DeletedUserId` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `CarClub`.`MeetTag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarClub`.`MeetTag` (
  `Id` BIGINT NOT NULL,
  `Code` VARCHAR(32) CHARACTER SET 'utf8mb4' NOT NULL,
  `Title` VARCHAR(128) CHARACTER SET 'utf8mb4' NOT NULL,
  `Note` VARCHAR(1024) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `CreatedIp` VARBINARY(16) NOT NULL,
  `CreatedUtc` DATETIME(6) NOT NULL,
  `CreatedUserId` BIGINT NOT NULL,
  `Updated` TINYINT(1) NOT NULL DEFAULT 0,
  `UpdatedIp` VARBINARY(16) NULL DEFAULT NULL,
  `UpdatedUtc` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedUserId` BIGINT NULL DEFAULT NULL,
  `Deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `DeletedIp` VARBINARY(16) NULL DEFAULT NULL,
  `DeletedUtc` DATETIME(6) NULL DEFAULT NULL,
  `DeletedUserId` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `FK_MeetTag_User_CreatedUserId` (`CreatedUserId` ASC) VISIBLE,
  INDEX `FK_MeetTag_User_UpdatedUserId` (`UpdatedUserId` ASC) VISIBLE,
  INDEX `FK_MeetTag_User_DeletedUserId` (`DeletedUserId` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `CarClub`.`MemberEvent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarClub`.`MemberEvent` (
  `Id` BIGINT NOT NULL,
  `MemberId` BIGINT NOT NULL,
  `EventId` BIGINT NOT NULL,
  `Register` TINYINT(1) NOT NULL DEFAULT 0,
  `RegisterIp` VARBINARY(16) NULL DEFAULT NULL,
  `RegisterUtc` DATETIME(6) NULL DEFAULT NULL,
  `RegisterBy` VARCHAR(128) CHARACTER SET 'utf8mb4' NOT NULL,
  `Checkin` TINYINT(1) NOT NULL DEFAULT 0,
  `CheckinIp` VARBINARY(16) NULL DEFAULT NULL,
  `CheckinUtc` DATETIME(6) NULL DEFAULT NULL,
  `CheckinBy` VARCHAR(128) CHARACTER SET 'utf8mb4' NOT NULL,
  `OnTrack` TINYINT(1) NOT NULL DEFAULT 0,
  `OnTrackIp` VARBINARY(16) NULL DEFAULT NULL,
  `OnTrackUtc` DATETIME(6) NULL DEFAULT NULL,
  `OnTrackBy` VARCHAR(128) CHARACTER SET 'utf8mb4' NOT NULL,
  `OffTrack` TINYINT(1) NOT NULL DEFAULT 0,
  `OffTrackIp` VARBINARY(16) NULL DEFAULT NULL,
  `OffTrackUtc` DATETIME(6) NULL DEFAULT NULL,
  `OffTrackBy` VARCHAR(128) CHARACTER SET 'utf8mb4' NOT NULL,
  `Checkout` TINYINT(1) NOT NULL DEFAULT 0,
  `CheckoutIp` VARBINARY(16) NULL DEFAULT NULL,
  `CheckoutUtc` DATETIME(6) NULL DEFAULT NULL,
  `CheckoutBy` VARCHAR(128) CHARACTER SET 'utf8mb4' NOT NULL,
  `CreatedIp` VARBINARY(16) NOT NULL,
  `CreatedUtc` DATETIME(6) NOT NULL,
  `CreatedUserId` BIGINT NOT NULL,
  `Updated` TINYINT(1) NOT NULL DEFAULT 0,
  `UpdatedIp` VARBINARY(16) NULL DEFAULT NULL,
  `UpdatedUtc` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedUserId` BIGINT NULL DEFAULT NULL,
  `Deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `DeletedIp` VARBINARY(16) NULL DEFAULT NULL,
  `DeletedUtc` DATETIME(6) NULL DEFAULT NULL,
  `DeletedUserId` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`));


-- -----------------------------------------------------
-- Table `CarClub`.`MemberEventAttachment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarClub`.`MemberEventAttachment` (
  `Id` BIGINT NOT NULL,
  `MemberEventId` BIGINT NOT NULL,
  `Filename` VARCHAR(128) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `Title` VARCHAR(128) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `Url` VARCHAR(256) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `CreatedIp` VARBINARY(16) NOT NULL,
  `CreatedUtc` DATETIME(6) NOT NULL,
  `CreatedUserId` BIGINT NOT NULL,
  `Updated` TINYINT(1) NOT NULL DEFAULT 0,
  `UpdatedIp` VARBINARY(16) NULL DEFAULT NULL,
  `UpdatedUtc` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedUserId` BIGINT NULL DEFAULT NULL,
  `Deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `DeletedIp` VARBINARY(16) NULL DEFAULT NULL,
  `DeletedUtc` DATETIME(6) NULL DEFAULT NULL,
  `DeletedUserId` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`));


-- -----------------------------------------------------
-- Table `CarClub`.`MemberEventStatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarClub`.`MemberEventStatus` (
  `Id` BIGINT NOT NULL,
  `Code` VARCHAR(32) CHARACTER SET 'utf8mb4' NOT NULL,
  `Title` VARCHAR(128) CHARACTER SET 'utf8mb4' NOT NULL,
  `Note` VARCHAR(1024) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `CreatedIp` VARBINARY(16) NOT NULL,
  `CreatedUtc` DATETIME(6) NOT NULL,
  `CreatedUserId` BIGINT NOT NULL,
  `Updated` TINYINT(1) NOT NULL DEFAULT 0,
  `UpdatedIp` VARBINARY(16) NULL DEFAULT NULL,
  `UpdatedUtc` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedUserId` BIGINT NULL DEFAULT NULL,
  `Deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `DeletedIp` VARBINARY(16) NULL DEFAULT NULL,
  `DeletedUtc` DATETIME(6) NULL DEFAULT NULL,
  `DeletedUserId` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `IX_Code` (`Deleted` ASC, `Code` ASC, `Title` ASC, `Updated` ASC) VISIBLE,
  INDEX `IX_Composite` (`Deleted` ASC, `Code` ASC, `Title` ASC, `Updated` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `CarClub`.`MemberMeet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarClub`.`MemberMeet` (
  `Id` BIGINT NOT NULL,
  `MemberId` BIGINT NOT NULL,
  `MeetId` BIGINT NOT NULL,
  `Enter` TINYINT(1) NOT NULL,
  `EnterIp` VARBINARY(16) NULL DEFAULT NULL,
  `EnterUtc` DATETIME(6) NULL DEFAULT NULL,
  `EnterBy` VARCHAR(128) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `Checkin` TINYINT(1) NOT NULL,
  `CheckinIp` VARBINARY(16) NOT NULL,
  `CheckinUtc` DATETIME(6) NOT NULL,
  `CheckinBy` VARCHAR(128) CHARACTER SET 'utf8mb4' NOT NULL,
  `Checkout` TINYINT(1) NOT NULL,
  `CheckoutIp` VARBINARY(16) NOT NULL,
  `CheckoutUtc` DATETIME(6) NOT NULL,
  `CheckoutBy` VARCHAR(128) CHARACTER SET 'utf8mb4' NOT NULL,
  `CreatedIp` VARBINARY(16) NOT NULL,
  `CreatedUtc` DATETIME(6) NOT NULL,
  `CreatedUserId` BIGINT NOT NULL,
  `Updated` TINYINT(1) NOT NULL DEFAULT 0,
  `UpdatedIp` VARBINARY(16) NULL DEFAULT NULL,
  `UpdatedUtc` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedUserId` BIGINT NULL DEFAULT NULL,
  `Deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `DeletedIp` VARBINARY(16) NULL DEFAULT NULL,
  `DeletedUtc` DATETIME(6) NULL DEFAULT NULL,
  `DeletedBy` TINYINT(1) NULL DEFAULT NULL,
  `DeletedUserId` BIGINT NULL,
  PRIMARY KEY (`Id`));


-- -----------------------------------------------------
-- Table `CarClub`.`MemberMeetAttachment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarClub`.`MemberMeetAttachment` (
  `Id` BIGINT NOT NULL,
  `MemberMeetId` BIGINT NOT NULL,
  `Filename` VARCHAR(128) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `Url` VARCHAR(256) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `CreatedIp` VARBINARY(16) NOT NULL,
  `CreatedUtc` DATETIME(6) NOT NULL,
  `CreatedUserId` BIGINT NOT NULL,
  `Updated` TINYINT(1) NOT NULL DEFAULT 0,
  `UpdatedIp` VARBINARY(16) NULL DEFAULT NULL,
  `UpdatedUtc` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedUserId` BIGINT NULL DEFAULT NULL,
  `Deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `DeletedIp` VARBINARY(16) NULL DEFAULT NULL,
  `DeletedUtc` DATETIME(6) NULL DEFAULT NULL,
  `DeletedUserId` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`));


-- -----------------------------------------------------
-- Table `CarClub`.`MemberMeetStatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarClub`.`MemberMeetStatus` (
  `Id` BIGINT NOT NULL,
  `Code` VARCHAR(32) CHARACTER SET 'utf8mb4' NOT NULL,
  `Title` VARCHAR(128) CHARACTER SET 'utf8mb4' NOT NULL,
  `Note` VARCHAR(1024) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `CreatedIp` VARBINARY(16) NOT NULL,
  `CreatedUtc` DATETIME(6) NOT NULL,
  `CreatedUserId` BIGINT NOT NULL,
  `Updated` TINYINT(1) NOT NULL DEFAULT 0,
  `UpdatedIp` VARBINARY(16) NULL DEFAULT NULL,
  `UpdatedUtc` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedUserId` BIGINT NULL DEFAULT NULL,
  `Deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `DeletedIp` VARBINARY(16) NULL DEFAULT NULL,
  `DeletedUtc` DATETIME(6) NULL DEFAULT NULL,
  `DeletedUserId` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`));


-- -----------------------------------------------------
-- Table `CarClub`.`MemberOffice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarClub`.`MemberOffice` (
  `Id` BIGINT NOT NULL,
  `MemberId` BIGINT NOT NULL,
  `OfficeId` BIGINT NOT NULL,
  `StartUtc` DATETIME(6) NULL DEFAULT NULL,
  `EndUtc` DATETIME(6) NULL DEFAULT NULL,
  `CreatedIp` VARBINARY(16) NOT NULL,
  `CreatedUtc` DATETIME(6) NOT NULL,
  `CreatedUserId` BIGINT NOT NULL,
  `Updated` TINYINT(1) NOT NULL DEFAULT 0,
  `UpdatedIp` VARBINARY(16) NULL DEFAULT NULL,
  `UpdatedUtc` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedUserId` BIGINT NULL DEFAULT NULL,
  `Deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `DeletedIp` VARBINARY(16) NULL DEFAULT NULL,
  `DeletedUtc` DATETIME(6) NULL DEFAULT NULL,
  `DeletedUserId` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`));


-- -----------------------------------------------------
-- Table `CarClub`.`MemberQualification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarClub`.`MemberQualification` (
  `Id` BIGINT NOT NULL,
  `MemberId` BIGINT NOT NULL,
  `QualificationId` BIGINT NOT NULL,
  `CreatedIp` VARBINARY(16) NOT NULL,
  `CreatedUtc` DATETIME(6) NOT NULL,
  `CreatedUserId` BIGINT NOT NULL,
  `Updated` TINYINT(1) NOT NULL DEFAULT 0,
  `UpdatedIp` VARBINARY(16) NULL DEFAULT NULL,
  `UpdatedUtc` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedUserId` BIGINT NULL DEFAULT NULL,
  `Deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `DeletedIp` VARBINARY(16) NULL DEFAULT NULL,
  `DeletedUtc` DATETIME(6) NULL DEFAULT NULL,
  `DeletedUserId` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `IX_QualificationId` (`QualificationId` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `CarClub`.`MemberTransaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarClub`.`MemberTransaction` (
  `Id` BIGINT NOT NULL,
  `MemberId` BIGINT NOT NULL,
  `WhenUtc` DATETIME(6) NOT NULL,
  `Description` VARCHAR(256) CHARACTER SET 'utf8mb4' NOT NULL,
  `Debit` DECIMAL(19,4) NOT NULL,
  `Credit` DECIMAL(19,4) NOT NULL,
  `Balance` DECIMAL(19,4) NOT NULL,
  `CreatedIp` VARBINARY(16) NOT NULL,
  `CreatedUtc` DATETIME(6) NOT NULL,
  `CreatedUserId` BIGINT NOT NULL,
  `Updated` TINYINT(1) NOT NULL DEFAULT 0,
  `UpdatedIp` VARBINARY(16) NULL DEFAULT NULL,
  `UpdatedUtc` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedUserId` BIGINT NULL DEFAULT NULL,
  `Deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `DeletedIp` VARBINARY(16) NULL DEFAULT NULL,
  `DeletedUtc` DATETIME(6) NULL DEFAULT NULL,
  `DeletedUserId` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`));


-- -----------------------------------------------------
-- Table `CarClub`.`MemberVehicle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarClub`.`MemberVehicle` (
  `Id` BIGINT NOT NULL,
  `MemberId` BIGINT NOT NULL,
  `VehicleId` BIGINT NOT NULL,
  `CreatedIp` VARBINARY(16) NOT NULL,
  `CreatedUtc` DATETIME(6) NOT NULL,
  `CreatedUserId` BIGINT NOT NULL,
  `Updated` TINYINT(1) NOT NULL DEFAULT 0,
  `UpdatedIp` VARBINARY(16) NULL DEFAULT NULL,
  `UpdatedUtc` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedUserId` BIGINT NULL DEFAULT NULL,
  `Deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `DeletedIp` VARBINARY(16) NULL DEFAULT NULL,
  `DeletedUtc` DATETIME(6) NULL DEFAULT NULL,
  `DeletedUserId` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`));


-- -----------------------------------------------------
-- Table `CarClub`.`Office`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarClub`.`Office` (
  `Id` BIGINT NOT NULL,
  `Code` VARCHAR(32) CHARACTER SET 'utf8mb4' NOT NULL,
  `Title` VARCHAR(128) CHARACTER SET 'utf8mb4' NOT NULL,
  `Note` VARCHAR(1024) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `CreatedUtc` DATETIME(6) NOT NULL,
  `CreatedIp` VARBINARY(16) NOT NULL,
  `CreatedUserId` BIGINT NOT NULL,
  `Updated` TINYINT(1) NOT NULL DEFAULT 0,
  `UpdatedIp` VARBINARY(16) NULL DEFAULT NULL,
  `UpdatedUtc` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedUserId` BIGINT NULL DEFAULT NULL,
  `Deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `DeletedIp` VARBINARY(16) NULL DEFAULT NULL,
  `DeletedUtc` DATETIME(6) NULL DEFAULT NULL,
  `DeletedUserId` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`));


-- -----------------------------------------------------
-- Table `CarClub`.`PenaltyAttachment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarClub`.`PenaltyAttachment` (
  `Id` BIGINT NOT NULL,
  `PenaltyId` BIGINT NOT NULL,
  `UploadIp` VARCHAR(32) CHARACTER SET 'utf8mb4' NOT NULL,
  `UploadUtc` DATETIME(6) NULL DEFAULT NULL,
  `UploadBy` VARCHAR(128) CHARACTER SET 'utf8mb4' NOT NULL,
  `Filename` VARCHAR(128) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `Url` VARCHAR(256) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `CreatedIp` VARBINARY(16) NOT NULL,
  `CreatedUtc` DATETIME(6) NOT NULL,
  `CreatedUserId` BIGINT NOT NULL,
  `Updated` TINYINT(1) NOT NULL DEFAULT 0,
  `UpdatedIp` VARBINARY(16) NULL DEFAULT NULL,
  `UpdatedUtc` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedUserId` BIGINT NULL DEFAULT NULL,
  `Deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `DeletedIp` VARBINARY(16) NULL DEFAULT NULL,
  `DeletedUtc` DATETIME(6) NULL DEFAULT NULL,
  `DeletedUserId` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`));


-- -----------------------------------------------------
-- Table `CarClub`.`Penalty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarClub`.`Penalty` (
  `Id` BIGINT NOT NULL,
  `HeatId` BIGINT NULL DEFAULT NULL,
  `DriverId` BIGINT NULL DEFAULT NULL,
  `VehicleId` BIGINT NULL DEFAULT NULL,
  `StatusId` BIGINT NULL DEFAULT NULL,
  `Code` VARCHAR(32) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `Title` VARCHAR(64) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `Notes` VARCHAR(1024) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `ValueMs` SMALLINT NULL DEFAULT NULL,
  `ValuePoints` SMALLINT NULL DEFAULT NULL,
  `CreatedIp` VARBINARY(16) NOT NULL,
  `CreatedUtc` DATETIME(6) NOT NULL,
  `CreatedUserId` BIGINT NOT NULL,
  `Updated` TINYINT(1) NOT NULL DEFAULT 0,
  `UpdatedIp` VARBINARY(16) NULL DEFAULT NULL,
  `UpdatedUtc` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedUserId` BIGINT NULL DEFAULT NULL,
  `Deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `DeletedIp` VARBINARY(16) NULL DEFAULT NULL,
  `DeletedUtc` DATETIME(6) NULL DEFAULT NULL,
  `DeletedUserId` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`));


-- -----------------------------------------------------
-- Table `CarClub`.`PenaltyReaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarClub`.`PenaltyReaction` (
  `Id` BIGINT NOT NULL,
  `PenaltyId` BIGINT NOT NULL,
  `MemberId` BIGINT NOT NULL,
  `Emoji` CHAR(1) CHARACTER SET 'utf8mb4' NOT NULL,
  `CreatedIp` VARBINARY(16) NOT NULL,
  `CreatedUtc` DATETIME(6) NOT NULL,
  `CreatedUserId` BIGINT NOT NULL,
  `Updated` TINYINT(1) NOT NULL DEFAULT 0,
  `UpdatedIp` VARBINARY(16) NULL DEFAULT NULL,
  `UpdatedUtc` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedUserId` BIGINT NULL DEFAULT NULL,
  `Deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `DeletedIp` VARBINARY(16) NULL DEFAULT NULL,
  `DeletedUtc` DATETIME(6) NULL DEFAULT NULL,
  `DeletedUserId` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`));


-- -----------------------------------------------------
-- Table `CarClub`.`Poll`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarClub`.`Poll` (
  `Id` BIGINT NOT NULL,
  `Title` VARCHAR(128) CHARACTER SET 'utf8mb4' NOT NULL,
  `Note` VARCHAR(1024) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `Open` TINYINT(1) NOT NULL DEFAULT 0,
  `OpenIp` VARBINARY(16) NULL DEFAULT NULL,
  `OpenUtc` DATETIME(6) NULL DEFAULT NULL,
  `OpenBy` VARCHAR(128) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `Closed` TINYINT(1) NOT NULL DEFAULT 0,
  `ClosedIp` VARBINARY(16) NULL DEFAULT NULL,
  `ClosedUtc` DATETIME(6) NULL DEFAULT NULL,
  `ClosedBy` VARCHAR(128) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `CreatedIp` VARBINARY(16) NOT NULL,
  `CreatedUtc` DATETIME(6) NOT NULL,
  `CreatedUserId` BIGINT NOT NULL,
  `Updated` TINYINT(1) NOT NULL DEFAULT 0,
  `UpdatedIp` VARBINARY(16) NULL DEFAULT NULL,
  `UpdatedUtc` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedUserId` BIGINT NULL DEFAULT NULL,
  `Deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `DeletedIp` VARBINARY(16) NULL DEFAULT NULL,
  `DeletedUtc` DATETIME(6) NULL DEFAULT NULL,
  `DeletedUserId` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`));


-- -----------------------------------------------------
-- Table `CarClub`.`PollOption`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarClub`.`PollOption` (
  `Id` BIGINT NOT NULL,
  `PollId` BIGINT NOT NULL,
  `Title` VARCHAR(128) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `CreatedIp` VARBINARY(16) NOT NULL,
  `CreatedUtc` DATETIME(6) NOT NULL,
  `CreatedUserId` BIGINT NOT NULL,
  `Updated` TINYINT(1) NOT NULL DEFAULT 0,
  `UpdatedIp` VARBINARY(16) NULL DEFAULT NULL,
  `UpdatedUtc` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedUserId` BIGINT NULL DEFAULT NULL,
  `Deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `DeletedIp` VARBINARY(16) NULL DEFAULT NULL,
  `DeletedUtc` DATETIME(6) NULL DEFAULT NULL,
  `DeletedUserId` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `FK_PollOption_Poll_PollId_idx` (`PollId` ASC) VISIBLE,
  CONSTRAINT `FK_PollOption_Poll_PollId`
    FOREIGN KEY (`PollId`)
    REFERENCES `CarClub`.`Poll` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `CarClub`.`Survey`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarClub`.`Survey` (
  `Id` BIGINT NOT NULL,
  `StatusId` BIGINT NOT NULL,
  `Title` VARCHAR(256) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `Note` VARCHAR(1024) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `CreatedIp` VARBINARY(16) NOT NULL,
  `CreatedUtc` DATETIME(6) NOT NULL,
  `CreatedUserId` BIGINT NOT NULL,
  `Updated` TINYINT(1) NOT NULL DEFAULT 0,
  `UpdatedIp` VARBINARY(16) NULL DEFAULT NULL,
  `UpdatedUtc` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedUserId` BIGINT NULL DEFAULT NULL,
  `Deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `DeletedIp` VARBINARY(16) NULL DEFAULT NULL,
  `DeletedUtc` DATETIME(6) NULL DEFAULT NULL,
  `DeletedUserId` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`));


-- -----------------------------------------------------
-- Table `CarClub`.`Post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarClub`.`Post` (
  `Id` BIGINT NOT NULL,
  `BoardId` BIGINT NOT NULL,
  `SurveyId` BIGINT NOT NULL DEFAULT NULL,
  `PollId` BIGINT NULL DEFAULT NULL,
  `CommentId` BIGINT NULL DEFAULT NULL,
  `Pinned` TINYINT(1) NOT NULL DEFAULT 0,
  `PinnedIp` VARBINARY(16) NULL DEFAULT NULL,
  `PinnedUtc` DATETIME(6) NULL DEFAULT NULL,
  `PinnedUserId` BIGINT NULL DEFAULT NULL,
  `PinnedNote` VARCHAR(1024) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `UnpinnedIp` VARBINARY(16) NULL DEFAULT NULL,
  `UnpinnedUtc` DATETIME(6) NULL DEFAULT NULL,
  `UnpinnedUserId` BIGINT NULL DEFAULT NULL,
  `UnpinnedNote` VARCHAR(1024) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `Locked` TINYINT(1) NOT NULL DEFAULT 0,
  `LockedIp` VARBINARY(16) NULL DEFAULT NULL,
  `LockedUtc` DATETIME(6) NULL DEFAULT NULL,
  `LockedUserId` BIGINT NULL DEFAULT NULL,
  `LockedNote` VARCHAR(1024) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `UnlockedIp` VARBINARY(16) NULL DEFAULT NULL,
  `UnlockedUtc` DATETIME(6) NULL DEFAULT NULL,
  `UnlockedUserId` BIGINT NULL DEFAULT NULL,
  `UnlockedNote` VARCHAR(1024) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `CreatedIp` VARBINARY(16) NOT NULL,
  `CreatedUtc` DATETIME(6) NOT NULL,
  `CreatedUserId` BIGINT NOT NULL,
  `Updated` TINYINT(1) NOT NULL DEFAULT 0,
  `UpdatedIp` VARBINARY(16) NULL DEFAULT NULL,
  `UpdatedUtc` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedUserId` BIGINT NULL DEFAULT NULL,
  `Deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `DeletedIp` VARBINARY(16) NULL DEFAULT NULL,
  `DeletedUtc` DATETIME(6) NULL DEFAULT NULL,
  `DeletedUserId` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `FK_Post_User_PinnedUserId_idx` (`PinnedUserId` ASC) VISIBLE,
  INDEX `FK_Post_User_UnpinnedUserId_idx` (`UnpinnedUserId` ASC) VISIBLE,
  INDEX `FK_Post_User_LockedUserId_idx` (`LockedUserId` ASC) VISIBLE,
  INDEX `FK_Post_User_UnlockedUserId_idx` (`UnlockedUserId` ASC) VISIBLE,
  INDEX `FK_Post_User_CreatedUserId_idx` (`CreatedUserId` ASC) VISIBLE,
  INDEX `FK_Post_User_UpdatedUserId_idx` (`UpdatedUserId` ASC) VISIBLE,
  INDEX `FK_Post_User_DeletedUserId_idx` (`DeletedUserId` ASC) VISIBLE,
  INDEX `FK_Post_Survey_SurveyId_idx` (`SurveyId` ASC) VISIBLE,
  INDEX `FK_Post_Poll_PollId_idx` (`PollId` ASC) VISIBLE,
  INDEX `FK_Post_Board_BoardId_idx` (`BoardId` ASC) VISIBLE,
  INDEX `FK_Post_Comment_CommentId_idx` (`CommentId` ASC) VISIBLE,
  CONSTRAINT `FK_Post_User_PinnedUserId`
    FOREIGN KEY (`PinnedUserId`)
    REFERENCES `CarClub`.`User` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Post_User_UnpinnedUserId`
    FOREIGN KEY (`UnpinnedUserId`)
    REFERENCES `CarClub`.`User` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Post_User_LockedUserId`
    FOREIGN KEY (`LockedUserId`)
    REFERENCES `CarClub`.`User` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Post_User_UnlockedUserId`
    FOREIGN KEY (`UnlockedUserId`)
    REFERENCES `CarClub`.`User` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Post_User_CreatedUserId`
    FOREIGN KEY (`CreatedUserId`)
    REFERENCES `CarClub`.`User` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Post_User_UpdatedUserId`
    FOREIGN KEY (`UpdatedUserId`)
    REFERENCES `CarClub`.`User` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Post_User_DeletedUserId`
    FOREIGN KEY (`DeletedUserId`)
    REFERENCES `CarClub`.`User` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Post_Survey_SurveyId`
    FOREIGN KEY (`SurveyId`)
    REFERENCES `CarClub`.`Survey` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Post_Poll_PollId`
    FOREIGN KEY (`PollId`)
    REFERENCES `CarClub`.`Poll` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Post_Board_BoardId`
    FOREIGN KEY (`BoardId`)
    REFERENCES `CarClub`.`Board` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Post_Comment_CommentId`
    FOREIGN KEY (`CommentId`)
    REFERENCES `CarClub`.`Comment` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `CarClub`.`Qualification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarClub`.`Qualification` (
  `Id` INT NOT NULL,
  `CreatedIp` VARBINARY(16) NULL,
  `CreatedUtc` DATETIME(6) NULL,
  `UpdatedIp` VARBINARY(16) NULL,
  `UpdatedUtc` DATETIME(6) NULL,
  `DeletedIp` VARBINARY(16) NULL,
  `DeletedUtc` DATETIME(6) NULL,
  `CreatedUserId` BIGINT NOT NULL,
  `UpdatedUserId` BIGINT NULL,
  `DeletedUserId` BIGINT NULL,
  PRIMARY KEY (`Id`));


-- -----------------------------------------------------
-- Table `CarClub`.`Role_copy1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarClub`.`Role_copy1` (
  `Id` BIGINT NOT NULL,
  `EventId` BIGINT NOT NULL,
  `Code` VARCHAR(32) CHARACTER SET 'utf8mb4' NOT NULL,
  `Title` VARCHAR(128) CHARACTER SET 'utf8mb4' NOT NULL,
  `Note` VARCHAR(1024) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `CreatedIp` VARBINARY(16) NOT NULL,
  `CreatedUtc` DATETIME(6) NOT NULL,
  `CreatedUserId` BIGINT NOT NULL,
  `Updated` TINYINT(1) NOT NULL DEFAULT 0,
  `UpdatedIp` VARBINARY(16) NULL DEFAULT NULL,
  `UpdatedUtc` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedUserId` BIGINT NULL DEFAULT NULL,
  `Deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `DeletedIp` VARBINARY(16) NULL DEFAULT NULL,
  `DeletedUtc` DATETIME(6) NULL DEFAULT NULL,
  `DeletedUserId` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `IX_EventId` (`EventId` ASC) VISIBLE,
  INDEX `FK_Role_User_CreatedUserId` (`CreatedUserId` ASC) VISIBLE,
  INDEX `FK_Role_User_UpdatedUserId` (`UpdatedUserId` ASC) VISIBLE,
  INDEX `FK_Role_User_DeletedUserId` (`DeletedUserId` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `CarClub`.`RoleCategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarClub`.`RoleCategory` (
  `Id` INT NOT NULL,
  `CreatedIp` VARBINARY(16) NULL,
  `CreatedUtc` DATETIME(6) NULL,
  `UpdatedIp` VARBINARY(16) NULL,
  `UpdatedUtc` DATETIME(6) NULL,
  `DeletedIp` VARBINARY(16) NULL,
  `DeletedUtc` DATETIME(6) NULL,
  `CreatedUserId` BIGINT NOT NULL,
  `UpdatedUserId` BIGINT NULL,
  `DeletedUserId` BIGINT NULL,
  PRIMARY KEY (`Id`));


-- -----------------------------------------------------
-- Table `CarClub`.`Season`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarClub`.`Season` (
  `Id` BIGINT NOT NULL,
  `StatusId` BIGINT NOT NULL,
  `Title` VARCHAR(128) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `Note` VARCHAR(1024) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `StartUtc` DATETIME(6) NULL DEFAULT NULL,
  `EndUtc` DATETIME(6) NULL DEFAULT NULL,
  `CreatedIp` VARBINARY(16) NOT NULL,
  `CreatedUtc` DATETIME(6) NOT NULL,
  `CreatedUserId` BIGINT NOT NULL,
  `Updated` TINYINT(1) NOT NULL DEFAULT 0,
  `UpdatedIp` VARBINARY(16) NULL DEFAULT NULL,
  `UpdatedUtc` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedUserId` BIGINT NULL DEFAULT NULL,
  `Deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `DeletedIp` VARBINARY(16) NULL DEFAULT NULL,
  `DeletedUtc` DATETIME(6) NULL DEFAULT NULL,
  `DeletedUserId` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`));


-- -----------------------------------------------------
-- Table `CarClub`.`SeasonAttachment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarClub`.`SeasonAttachment` (
  `Id` BIGINT NOT NULL,
  `SeasonId` BIGINT NOT NULL,
  `Filename` VARCHAR(128) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `Url` VARCHAR(256) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `CreatedIp` VARBINARY(16) NOT NULL,
  `CreatedUtc` DATETIME(6) NOT NULL,
  `CreatedUserId` BIGINT NOT NULL,
  `Updated` TINYINT(1) NOT NULL DEFAULT 0,
  `UpdatedIp` VARBINARY(16) NULL DEFAULT NULL,
  `UpdatedUtc` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedUserId` BIGINT NULL DEFAULT NULL,
  `Deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `DeletedIp` VARBINARY(16) NULL DEFAULT NULL,
  `DeletedUtc` DATETIME(6) NULL DEFAULT NULL,
  `DeletedUserId` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`));


-- -----------------------------------------------------
-- Table `CarClub`.`SeasonEvent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarClub`.`SeasonEvent` (
  `Id` BIGINT NOT NULL,
  `SeasonId` BIGINT NOT NULL,
  `EventId` BIGINT NOT NULL,
  `CreatedIp` VARBINARY(16) NOT NULL,
  `CreatedUtc` DATETIME(6) NOT NULL,
  `CreatedUserId` BIGINT NOT NULL,
  `Updated` TINYINT(1) NOT NULL DEFAULT 0,
  `UpdatedIp` VARBINARY(16) NULL DEFAULT NULL,
  `UpdatedUtc` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedUserId` BIGINT NULL DEFAULT NULL,
  `Deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `DeletedIp` VARBINARY(16) NULL DEFAULT NULL,
  `DeletedUtc` DATETIME(6) NULL DEFAULT NULL,
  `DeletedUserId` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`));


-- -----------------------------------------------------
-- Table `CarClub`.`SeasonEventReward`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarClub`.`SeasonEventReward` (
  `Id` BIGINT NOT NULL,
  `SeasonEventId` BIGINT NOT NULL,
  `Position` TINYINT UNSIGNED NULL DEFAULT NULL,
  `Percentile` DOUBLE NULL DEFAULT NULL,
  `Value` SMALLINT NULL DEFAULT NULL,
  `Note` VARCHAR(1024) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `CreatedIp` VARBINARY(16) NOT NULL,
  `CreatedUtc` DATETIME(6) NOT NULL,
  `CreatedUserId` BIGINT NOT NULL,
  `Updated` TINYINT(1) NOT NULL DEFAULT 0,
  `UpdatedIp` VARBINARY(16) NULL DEFAULT NULL,
  `UpdatedUtc` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedUserId` BIGINT NULL DEFAULT NULL,
  `Deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `DeletedIp` VARBINARY(16) NULL DEFAULT NULL,
  `DeletedUtc` DATETIME(6) NULL DEFAULT NULL,
  `DeletedBy` TINYINT(1) NULL DEFAULT NULL,
  `DeletedUserId` BIGINT NULL,
  PRIMARY KEY (`Id`));


-- -----------------------------------------------------
-- Table `CarClub`.`SeasonEventStatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarClub`.`SeasonEventStatus` (
  `Id` BIGINT NOT NULL,
  `Code` VARCHAR(32) CHARACTER SET 'utf8mb4' NOT NULL,
  `Title` VARCHAR(128) CHARACTER SET 'utf8mb4' NOT NULL,
  `Note` VARCHAR(1024) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `CreatedIp` VARBINARY(16) NOT NULL,
  `CreatedUtc` DATETIME(6) NOT NULL,
  `CreatedUserId` BIGINT NOT NULL,
  `Updated` TINYINT(1) NOT NULL DEFAULT 0,
  `UpdatedIp` VARBINARY(16) NULL DEFAULT NULL,
  `UpdatedUtc` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedUserId` BIGINT NULL DEFAULT NULL,
  `Deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `DeletedIp` VARBINARY(16) NULL DEFAULT NULL,
  `DeletedUtc` DATETIME(6) NULL DEFAULT NULL,
  `DeletedUserId` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`));


-- -----------------------------------------------------
-- Table `CarClub`.`SeasonStatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarClub`.`SeasonStatus` (
  `Id` BIGINT NOT NULL,
  `Code` VARCHAR(32) CHARACTER SET 'utf8mb4' NOT NULL,
  `Title` VARCHAR(128) CHARACTER SET 'utf8mb4' NOT NULL,
  `Note` VARCHAR(1024) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `CreatedIp` VARBINARY(16) NOT NULL,
  `CreatedUtc` DATETIME(6) NOT NULL,
  `CreatedUserId` BIGINT NOT NULL,
  `Updated` TINYINT(1) NOT NULL DEFAULT 0,
  `UpdatedIp` VARBINARY(16) NULL DEFAULT NULL,
  `UpdatedUtc` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedUserId` BIGINT NULL DEFAULT NULL,
  `Deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `DeletedIp` VARBINARY(16) NULL DEFAULT NULL,
  `DeletedUtc` DATETIME(6) NULL DEFAULT NULL,
  `DeletedUserId` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `IX_Composite` (`Deleted` ASC, `Code` ASC, `Title` ASC, `Updated` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `CarClub`.`SurveyOption`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarClub`.`SurveyOption` (
  `Id` BIGINT NOT NULL,
  `QuestionId` BIGINT NOT NULL,
  `Position` TINYINT UNSIGNED NULL DEFAULT NULL,
  `Title` VARCHAR(128) CHARACTER SET 'utf8mb4' NOT NULL,
  `Note` VARCHAR(1024) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `CreatedIp` VARBINARY(16) NOT NULL,
  `CreatedUtc` DATETIME(6) NOT NULL,
  `CreatedUserId` BIGINT NOT NULL,
  `Updated` TINYINT(1) NOT NULL DEFAULT 0,
  `UpdatedIp` VARBINARY(16) NULL DEFAULT NULL,
  `UpdatedUtc` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedUserId` BIGINT NULL DEFAULT NULL,
  `Deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `DeletedIp` VARBINARY(16) NULL DEFAULT NULL,
  `DeletedUtc` DATETIME(6) NULL DEFAULT NULL,
  `DeletedUserId` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`));


-- -----------------------------------------------------
-- Table `CarClub`.`SurveyQuestion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarClub`.`SurveyQuestion` (
  `Id` BIGINT NOT NULL,
  `SurveyId` BIGINT NOT NULL,
  `Position` TINYINT UNSIGNED NULL DEFAULT NULL,
  `Title` VARCHAR(256) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `Note` VARCHAR(1024) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `Text` TINYINT(1) NULL DEFAULT NULL,
  `Int` TINYINT(1) NULL DEFAULT NULL,
  `IntMin` SMALLINT NULL DEFAULT NULL,
  `IntMax` SMALLINT NULL DEFAULT NULL,
  `IntSteps` TINYINT UNSIGNED NULL DEFAULT NULL,
  `CreatedIp` VARBINARY(16) NOT NULL,
  `CreatedUtc` DATETIME(6) NOT NULL,
  `CreatedUserId` BIGINT NOT NULL,
  `Updated` TINYINT(1) NOT NULL DEFAULT 0,
  `UpdatedIp` VARBINARY(16) NULL DEFAULT NULL,
  `UpdatedUtc` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedUserId` BIGINT NULL DEFAULT NULL,
  `Deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `DeletedIp` VARBINARY(16) NULL DEFAULT NULL,
  `DeletedUtc` DATETIME(6) NULL DEFAULT NULL,
  `DeletedUserId` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`));


-- -----------------------------------------------------
-- Table `CarClub`.`SurveyResponse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarClub`.`SurveyResponse` (
  `Id` BIGINT NOT NULL,
  `SurveyQuestionId` BIGINT NOT NULL,
  `MemberId` BIGINT NOT NULL,
  `OptionId` BIGINT NULL DEFAULT NULL,
  `IntValue` SMALLINT NULL DEFAULT NULL,
  `Note` VARCHAR(1024) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `CreatedUtc` DATETIME(6) NOT NULL,
  `CreatedIp` VARBINARY(16) NOT NULL,
  `CreatedUserId` BIGINT NOT NULL,
  `Updated` TINYINT(1) NOT NULL DEFAULT 0,
  `UpdatedIp` VARBINARY(16) NULL DEFAULT NULL,
  `UpdatedUtc` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedUserId` BIGINT NULL DEFAULT NULL,
  `Deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `DeletedIp` VARBINARY(16) NULL DEFAULT NULL,
  `DeletedUtc` DATETIME(6) NULL DEFAULT NULL,
  `DeletedUserId` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `IX_QuestionId` (`SurveyQuestionId` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `CarClub`.`SurveyStatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarClub`.`SurveyStatus` (
  `Id` BIGINT NOT NULL,
  `Code` VARCHAR(32) CHARACTER SET 'utf8mb4' NOT NULL,
  `Title` VARCHAR(128) CHARACTER SET 'utf8mb4' NOT NULL,
  `Note` VARCHAR(1024) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `CreatedIp` VARBINARY(16) NOT NULL,
  `CreatedUtc` DATETIME(6) NOT NULL,
  `CreatedUserId` BIGINT NOT NULL,
  `Updated` TINYINT(1) NOT NULL DEFAULT 0,
  `UpdatedIp` VARBINARY(16) NULL DEFAULT NULL,
  `UpdatedUtc` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedUserId` BIGINT NULL DEFAULT NULL,
  `Deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `DeletedIp` VARBINARY(16) NULL DEFAULT NULL,
  `DeletedUtc` DATETIME(6) NULL DEFAULT NULL,
  `DeletedUserId` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`));


-- -----------------------------------------------------
-- Table `CarClub`.`Tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarClub`.`Tag` (
  `Id` BIGINT NOT NULL,
  `CreatorId` BIGINT NOT NULL,
  `OwnerId` BIGINT NOT NULL,
  `StatusId` BIGINT NOT NULL,
  `Title` VARCHAR(256) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `Note` VARCHAR(1024) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `CreatedIp` VARBINARY(16) NOT NULL,
  `CreatedUtc` DATETIME(6) NOT NULL,
  `CreatedUserId` BIGINT NOT NULL,
  `Updated` TINYINT(1) NOT NULL DEFAULT 0,
  `UpdatedIp` VARBINARY(16) NULL DEFAULT NULL,
  `UpdatedUtc` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedUserId` BIGINT NULL DEFAULT NULL,
  `Deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `DeletedIp` VARBINARY(16) NULL DEFAULT NULL,
  `DeletedUtc` DATETIME(6) NULL DEFAULT NULL,
  `DeletedUserId` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`));


-- -----------------------------------------------------
-- Table `CarClub`.`TagStatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarClub`.`TagStatus` (
  `Id` BIGINT NOT NULL,
  `Code` VARCHAR(32) CHARACTER SET 'utf8mb4' NOT NULL,
  `Title` VARCHAR(128) CHARACTER SET 'utf8mb4' NOT NULL,
  `Note` VARCHAR(1024) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `CreatedIp` VARBINARY(16) NOT NULL,
  `CreatedUtc` DATETIME(6) NOT NULL,
  `CreatedUserId` BIGINT NOT NULL,
  `Updated` TINYINT(1) NOT NULL DEFAULT 0,
  `UpdatedIp` VARBINARY(16) NULL DEFAULT NULL,
  `UpdatedUtc` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedUserId` BIGINT NULL DEFAULT NULL,
  `Deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `DeletedIp` VARBINARY(16) NULL DEFAULT NULL,
  `DeletedUtc` DATETIME(6) NULL DEFAULT NULL,
  `DeletedUserId` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `IX_Composite` (`Deleted` ASC, `Code` ASC, `Title` ASC, `Updated` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `CarClub`.`Vehicle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarClub`.`Vehicle` (
  `Id` BIGINT NOT NULL,
  `StatusId` BIGINT NOT NULL,
  `MakeId` BIGINT NULL DEFAULT NULL,
  `ModelId` BIGINT NULL DEFAULT NULL,
  `VariantId` BIGINT NULL DEFAULT NULL,
  `Year` SMALLINT NULL DEFAULT NULL,
  `Title` VARCHAR(128) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `Note` VARCHAR(1024) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `CreatedIp` VARBINARY(16) NOT NULL,
  `CreatedUtc` DATETIME(6) NOT NULL,
  `CreatedUserId` BIGINT NOT NULL,
  `Updated` TINYINT(1) NOT NULL DEFAULT 0,
  `UpdatedIp` VARBINARY(16) NULL DEFAULT NULL,
  `UpdatedUtc` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedUserId` BIGINT NULL DEFAULT NULL,
  `Deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `DeletedIp` VARBINARY(16) NULL DEFAULT NULL,
  `DeletedUtc` DATETIME(6) NULL DEFAULT NULL,
  `DeletedUserId` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`));


-- -----------------------------------------------------
-- Table `CarClub`.`VehicleAttachment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarClub`.`VehicleAttachment` (
  `Id` BIGINT NOT NULL,
  `VehicleId` BIGINT NOT NULL,
  `Filename` VARCHAR(128) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `Url` VARCHAR(256) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `CreatedIp` VARBINARY(16) NOT NULL,
  `CreatedUtc` DATETIME(6) NOT NULL,
  `CreatedUserId` BIGINT NOT NULL,
  `Updated` TINYINT(1) NOT NULL DEFAULT 0,
  `UpdatedIp` VARBINARY(16) NULL DEFAULT NULL,
  `UpdatedUtc` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedUserId` BIGINT NULL DEFAULT NULL,
  `Deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `DeletedIp` VARBINARY(16) NULL DEFAULT NULL,
  `DeletedUtc` DATETIME(6) NULL DEFAULT NULL,
  `DeletedUserId` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`));


-- -----------------------------------------------------
-- Table `CarClub`.`VehicleMake`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarClub`.`VehicleMake` (
  `Id` BIGINT NOT NULL,
  `Code` VARCHAR(32) CHARACTER SET 'utf8mb4' NOT NULL,
  `Title` VARCHAR(128) CHARACTER SET 'utf8mb4' NOT NULL,
  `Note` VARCHAR(1024) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `CreatedIp` VARBINARY(16) NOT NULL,
  `CreatedUtc` DATETIME(6) NOT NULL,
  `CreatedUserId` BIGINT NOT NULL,
  `Updated` TINYINT(1) NOT NULL DEFAULT 0,
  `UpdatedIp` VARBINARY(16) NULL DEFAULT NULL,
  `UpdatedUtc` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedUserId` BIGINT NULL DEFAULT NULL,
  `Deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `DeletedIp` VARBINARY(16) NULL DEFAULT NULL,
  `DeletedUtc` DATETIME(6) NULL DEFAULT NULL,
  `DeletedUserId` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`));


-- -----------------------------------------------------
-- Table `CarClub`.`VehicleModel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarClub`.`VehicleModel` (
  `Id` BIGINT NOT NULL,
  `MakeId` BIGINT NOT NULL,
  `Code` VARCHAR(32) CHARACTER SET 'utf8mb4' NOT NULL,
  `Title` VARCHAR(128) CHARACTER SET 'utf8mb4' NOT NULL,
  `Note` VARCHAR(1024) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `CreatedIp` VARBINARY(16) NOT NULL,
  `CreatedUtc` DATETIME(6) NOT NULL,
  `CreatedUserId` BIGINT NOT NULL,
  `Updated` TINYINT(1) NOT NULL DEFAULT 0,
  `UpdatedIp` VARBINARY(16) NULL DEFAULT NULL,
  `UpdatedUtc` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedUserId` BIGINT NULL DEFAULT NULL,
  `Deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `DeletedIp` VARBINARY(16) NULL DEFAULT NULL,
  `DeletedUtc` DATETIME(6) NULL DEFAULT NULL,
  `DeletedUserId` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`));


-- -----------------------------------------------------
-- Table `CarClub`.`VehicleOwner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarClub`.`VehicleOwner` (
  `Id` BIGINT NOT NULL,
  `MemberId` BIGINT NULL DEFAULT NULL,
  `Note` VARCHAR(1024) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `CreatedIp` VARBINARY(16) NOT NULL,
  `CreatedUtc` DATETIME(6) NOT NULL,
  `CreatedUserId` BIGINT NOT NULL,
  `Updated` TINYINT(1) NOT NULL DEFAULT 0,
  `UpdatedIp` VARBINARY(16) NULL DEFAULT NULL,
  `UpdatedUtc` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedUserId` BIGINT NULL DEFAULT NULL,
  `Deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `DeletedIp` VARBINARY(16) NULL DEFAULT NULL,
  `DeletedUtc` DATETIME(6) NULL DEFAULT NULL,
  `DeletedUserId` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`));


-- -----------------------------------------------------
-- Table `CarClub`.`VehicleReaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarClub`.`VehicleReaction` (
  `Id` BIGINT NOT NULL,
  `VehicleId` BIGINT NOT NULL,
  `MemberId` BIGINT NOT NULL,
  `Emoji` CHAR(1) CHARACTER SET 'utf8mb4' NOT NULL,
  `CreatedIp` VARBINARY(16) NOT NULL,
  `CreatedUtc` DATETIME(6) NOT NULL,
  `CreatedUserId` BIGINT NOT NULL,
  `Updated` TINYINT(1) NOT NULL DEFAULT 0,
  `UpdatedIp` VARBINARY(16) NULL DEFAULT NULL,
  `UpdatedUtc` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedUserId` BIGINT NULL DEFAULT NULL,
  `Deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `DeletedIp` VARBINARY(16) NULL DEFAULT NULL,
  `DeletedUtc` DATETIME(6) NULL DEFAULT NULL,
  `DeletedUserId` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`));


-- -----------------------------------------------------
-- Table `CarClub`.`VehicleStatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarClub`.`VehicleStatus` (
  `Id` BIGINT NOT NULL,
  `Code` VARCHAR(32) CHARACTER SET 'utf8mb4' NOT NULL,
  `Title` VARCHAR(128) CHARACTER SET 'utf8mb4' NOT NULL,
  `Note` VARCHAR(1024) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `CreatedIp` VARBINARY(16) NOT NULL,
  `CreatedUtc` DATETIME(6) NOT NULL,
  `CreatedUserId` BIGINT NOT NULL,
  `Updated` TINYINT(1) NOT NULL DEFAULT 0,
  `UpdatedIp` VARBINARY(16) NULL DEFAULT NULL,
  `UpdatedUtc` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedUserId` BIGINT NULL DEFAULT NULL,
  `Deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `DeletedIp` VARBINARY(16) NULL DEFAULT NULL,
  `DeletedUtc` DATETIME(6) NULL DEFAULT NULL,
  `DeletedUserId` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`));


-- -----------------------------------------------------
-- Table `CarClub`.`VehicleVariant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarClub`.`VehicleVariant` (
  `Id` BIGINT NOT NULL,
  `ModelId` BIGINT NOT NULL,
  `Code` VARCHAR(32) CHARACTER SET 'utf8mb4' NOT NULL,
  `Title` VARCHAR(128) CHARACTER SET 'utf8mb4' NOT NULL,
  `Note` VARCHAR(1024) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `CreatedIp` VARBINARY(16) NOT NULL,
  `CreatedUtc` DATETIME(6) NOT NULL,
  `CreatedUserId` BIGINT NOT NULL,
  `Updated` TINYINT(1) NOT NULL DEFAULT 0,
  `UpdatedIp` VARBINARY(16) NULL DEFAULT NULL,
  `UpdatedUtc` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedUserId` BIGINT NULL DEFAULT NULL,
  `Deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `DeletedIp` VARBINARY(16) NULL DEFAULT NULL,
  `DeletedUtc` DATETIME(6) NULL DEFAULT NULL,
  `DeletedUserId` BIGINT NULL DEFAULT NULL,
  `CreatedUtc` DATETIME(6) NULL,
  `CreatedUtc` DATETIME(6) NULL,
  `CreatedUtc` DATETIME(6) NULL,
  `CreatedUtc` DATETIME(6) NULL,
  `CreatedUtc` DATETIME(6) NULL,
  `CreatedUtc` DATETIME(6) NULL,
  PRIMARY KEY (`Id`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
